### ISSUE TITLE
On mobile/small screen: move sidebar for support/about BELOW header on landing page. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#102]

**Comment by JosephMcArthur** [comment]
Let's actually just move it below the first header (which says "support")

I could also be convinced this isn't a good idea.

**Comment by JosephMcArthur** [comment]
@markmacgillivray anything blocking here?

**Comment by markmacgillivray** [comment]
Ah I don't think I did this one, was it initially assigned to someone else? It is a content fix. I can make the change now though, will move to current milestone for clarity.
