### ISSUE TITLE
Put up OAB Story and ODB slider

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#104]
Following: https://github.com/OAButton/backend/commit/abb94068a16df5f3c9929421f5347ed660045376

**Comment by chealsye** [comment]
Added in the corrected quote slider from Himmelstein to Pollock. https://github.com/OAButton/backend/commit/0c89f4c33ec97fb5b1288ee8e1a0b47db03a64b1

**Comment by mtb-za** [comment]
Can I delete the Himmelstein ones then? (So Rufus Pollock is the right attribution?)

Are these being used anywhere yet? I want to drop them in a new folder within `portality/static/`, but do not want to break anything yet.

**Comment by chealsye** [comment]
Martin,

Yes, the Himmelstein ones can be deleted. The Pollock one is being used on
the ODB website slider.

Best,
Chealsye
