### ISSUE TITLE
Search Zenodo for papers

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#110]
add a /use endpoint

**Comment by markmacgillivray** [comment]
Zenodo is already added as a /use endpoint so we can deposit to it, but in looking through their API docs for search info, then checking their feature list, I find that they do not have a search API yet. 

See https://zenodo.org/features

So if we are covered with this via SHARE, not a problem; if not, then we wait and see.

So I am moving this out from the current milestone, as it cannot be completed yet but may become relevant again later.

**Comment by JosephMcArthur** [comment]
Can we use the OAI-PMH link(https://zenodo.org/dev) & find out when their extended API will be released (&if we can help them test behind the scenes for earlier access).

**Comment by markmacgillivray** [comment]
We can use oai-pmh, it is just a bit more work than using the API - it is not hard in itself, but we just have not yet written in any oai-pmh yet. So I will get this done if there is time, but if it requires more time it will have to continue into the next milestone.

For getting more info on when they will release, and potentially testing for them, do you want to contact them @JosephMcArthur or shall I?

**Comment by JosephMcArthur** [comment]
Okay Zenodo is searched by Openaire. So if we close #107 then this is also good. Closing.
