### ISSUE TITLE
Layout technical plan for automated email gathering? 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#118]
- [x] What UI changes are needed? 
- [x] Implement in the plug-ins or backend (backend is my preference)
- [x] What's the 80/20 implementation? Are some sites going to be really easy, which are going to be hard?

**Comment by JosephMcArthur** [comment]
@markmacgillivray we've done much of this issue in our chat about #188. However, I'm suggesting that for this sprint we aim to:
- [ ] Implement easy forms of email gathering for some pages
and hopefully finish the first comment on this issue.

**Comment by markmacgillivray** [comment]
Moving to next sprint along with #188

**Comment by markmacgillivray** [comment]
Still to do large scale analysis

**Comment by JosephMcArthur** [comment]
Planning to shift this to post-plugin dev freeze #230 as I expect it should happen on the backend - not the plugin.

**Comment by JosephMcArthur** [comment]
This seems to be working in many cases, suggest we close and report bugs where required.
