### ISSUE TITLE
Have the plugins understand pubmed pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#120]

**Comment by JosephMcArthur** [comment]
@Steven-Eardley should we think about this as part of the rebuild?

**Comment by Steven-Eardley** [comment]
I'll keep it in mind, but it's for testing near the end of the process.

**Comment by JosephMcArthur** [comment]
Thanks!

**Comment by markmacgillivray** [comment]
And probably any understanding of pages should move to a backend function,
and be as generic as possible, and the plugins should call it

**Comment by JosephMcArthur** [comment]
+1

**Comment by JosephMcArthur** [comment]
This works now!
