### ISSUE TITLE
Clean up OAB action page

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#123]
https://openaccessbutton.org/action

Following issues for the action page

1. The first button (orange rectangle 'button') below "x people need access to research" has no headline text and just simply "or contact us directly." 

Suggestions:
Headline the button with: Contact us
Linked text below: Get in touch on Twitter, Facebook, or email us directly.

url to hyperlink Twitter = https://twitter.com/OA_Button
Facebook = https://www.facebook.com/openaccessbutton
Email us directly = https://openaccessbutton.org/contact

2. Get connected 
Change "Sign up to our mailing list here" to simply "Sign up to our mailing list" and change the url colour to the dark blue of other button links.

Would it be possible to make these three orange buttons on the page all the same size? 

3. Remove the data requests listed at the bottom of the page. They aren't cleaned up for tests, they're infinite when scrolling, and that's what we have the requests page for.

**Comment by JosephMcArthur** [comment]
Have cleaned up buttons and hidden stories till they're working better.

**Comment by JosephMcArthur** [comment]
This is linked to #131

**Comment by chealsye** [comment]
"Suggestions:
Headline the button with: Contact us
Linked text below: Get in touch on Twitter, Facebook, or email us directly.

url to hyperlink Twitter = https://twitter.com/OA_Button
Facebook = https://www.facebook.com/openaccessbutton
Email us directly = https://openaccessbutton.org/contact

Get connected Change "Sign up to our mailing list here" to simply "Sign up to our mailing list" and change the url colour to the dark blue of other button links."

@JosephMcArthur Do you want these as two new buttons?

**Comment by JosephMcArthur** [comment]
Nope, they're not needed!

**Comment by markmacgillivray** [comment]
Not sure what I can do with this one, and #131 covers the relevant points for me, so unassigning to keep track of what I need to do.

**Comment by JosephMcArthur** [comment]
@markmacgillivray this issue lives here until #131 is shut. Then I can unhide stories from the page.

**Comment by JosephMcArthur** [comment]
Will look at this later in the week.

**Comment by JosephMcArthur** [comment]
@markmacgillivray this looks so much better, which is great. The thing we really now have left to solve is that duplicate URL's are still being shown from (what I assume is) the same user. This feels like not a big challenge to solve, but let me know if it is. 

Once that's done, and we're in the habit of cleaning #187 these lists will be much better.

**Comment by markmacgillivray** [comment]
Hmm, thought I removed these, will check. Moving to current milestone.

**Comment by markmacgillivray** [comment]
Now happening as part of new site dev, moving on to next milestone for further checks

**Comment by JosephMcArthur** [comment]
Okay, no longer seeing duplicate URL's from a user & my comment on stories is not longer applicable. Closing for now however #187 remains an issue.
