### ISSUE TITLE
OAB Request Page

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#124]
https://openaccessbutton.org/request

The OAB request page displays ODB requests. 

If we're not using the requests page for a click through map or to highly stories, could we get rid of the requests page or quiet it for now?

**Comment by JosephMcArthur** [comment]
The actual request pages are using the oab skin too.

**Comment by markmacgillivray** [comment]
This is actually just an error in the content the request displays, but the listing works properly. The fix is already done for another issue, and will be pushed to live imminently. Closing this one.
