### ISSUE TITLE
Note code licence on footer

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#125]

**Comment by markmacgillivray** [comment]
Footer can be edited from the static content sites, so I'll leave that to you guys to do, just so I don't commit to master and cause a merge conflict with all the other ones you've already been working on. At the top level of the oab_static and odb_static repos there is a file called index.html and down near the bottom there is the definition of the footer.

**Comment by markmacgillivray** [comment]
Maybe the code licence should just be mentioned in the API docs though, where the code is linked from as I suggest in issue about API docs page, which I will create.

**Comment by JosephMcArthur** [comment]
Okay
