### ISSUE TITLE
Move API code into an OAB repo or at least describe location in readme

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#126]

**Comment by markmacgillivray** [comment]
In which readme, in which repo? This one? Or the oab_static and odb_static ones? It may be better just having the link to the code mentioned in the API docs page. But actually, although the code is open source, it is not actually the sort of thing that would be of use to anyone to view, unless they want to start contributing. But again, such people would have to at least be using the API, so may as well go on the API docs page if anywhere.
