### ISSUE TITLE
Header bar and landing screen are bad on mobile

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#127]
Nav bar doesn't function well and general appearance is sloppy. I'd suggest at least: 

- [x] hiding slider
- [x] logo and name appear on same line

**Comment by markmacgillivray** [comment]
Have removed logo but put title on the nav strap, and improved the nav layout so it drops down nicely under that. Removed slider and altered button display so it makes sense now to read down the page and get the button / do other things. Edited for oab and odb.
