### ISSUE TITLE
No favicon's on openaccessbutton.org

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#129]

**Comment by JosephMcArthur** [comment]
fwiw, it's on develop.

**Comment by markmacgillivray** [comment]
Appears now

**Comment by JosephMcArthur** [comment]
They don't seem to appear on request pages, thats on open access and open data button.

**Comment by markmacgillivray** [comment]
Ah yes there is a bug there, they show on other pages but not the request or account pages. I will need to work on a more complex solution for that.

**Comment by markmacgillivray** [comment]
Fixed, to deploy to live later today
