### ISSUE TITLE
Navbar links are in a weird order for open access button

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#130]
I'd suggest: take action, requests, support, about, blog, login, download

**Comment by markmacgillivray** [comment]
You have control of these too, as with the request about changing the footer. From the static repos, via the index.html page. Near the top of the body section you will see the nav links.

**Comment by markmacgillivray** [comment]
Re this one and the footer one that I assigned to you, I don't mind doing them later, but first it would be better if you and Chealsye can merge all your develop changes into the master branches for oab_static and odb_static, then I will make some changes later tonight. Or else make them yourself in your Develop / or other branches, and they will become live when you push to master.
