### ISSUE TITLE
Duplicates and other junk on /action pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#131]
The stories don't seem to be filtering out URLs which should get hidden (e.g google or our own site). I know about the duplicate story logging issue, can we make a quick-ish fix at all?

**Comment by JosephMcArthur** [comment]
I've hidden this till the issue is resolved.

**Comment by markmacgillivray** [comment]
Will prioritise this as next task for me to do, and to fix the duplication problem. But right now I have to be elsewhere.

**Comment by markmacgillivray** [comment]
OK, some old messy ones have now been cleared up. The system now refuses duplicates of URLs from the same user, and automatically tags some blocks/requests as test, even if the user account submitting them is not a test account, but if they URL was on CL or OAB sites or google chrome etc, and similarly if the email address is a CL one or a Joe one.

**Comment by JosephMcArthur** [comment]
Thanks, Mark. This sounds much better. If needed can I send you URLs / Emails that need to get filtered? Or, could you stick a box in the UI somewhere I could drop them?

**Comment by markmacgillivray** [comment]
Yeah for now just send to me. I can rerun whenever necessary now.
