### ISSUE TITLE
Vary size of area for stories on request pages depending on number of stories

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#134]

**Comment by markmacgillivray** [comment]
I think it already does vary. But the columns on the right, with the text, are longer - so they stay longer. I could put the text columns underneath, but then if there are lots of stories nobody will see the text unless they scroll down. Hence why they are laid out in the current fashion - it is the only way to bring them nearer the top on a wide screen, and to push them below the more important supporting stories on a small screen. Don't know if much can be done about this, @JosephMcArthur

**Comment by markmacgillivray** [comment]
I've checked, it does vary. Nothing further to do on the technical side here, unless you let me know about changes to content.

**Comment by JosephMcArthur** [comment]
I'd suggest we move the "What's Open Data, and why should I care?" on ODB under the story box, so it's full width. Then, we could have "How else you can help" and "share this request" next to the stories (same width) but follow the screen on scroll, so they're always present. This would still have the page look nice and have key actions in view regardless of how many stories are present.

**Comment by markmacgillivray** [comment]
That would be bad for mobile though, it would make the add support option come away down under the list of stories, which could potentially be long although is not yet for any requests. Current layout ensures ordering of key content on small and large screens. "What's open data and why should I care" section could be pushed under the stories list and to full width though. @JosephMcArthur let me know if you'd be happy with that and I will make this my next change, but cannot do more tonight.

**Comment by JosephMcArthur** [comment]
Discussed approach with this with @markmacgillivray yesterday. Floating support requests follow on large screens, but page appears as it currently does on mobile.

**Comment by markmacgillivray** [comment]
Removed "how else to help" section, it really just duplicates the content of "share this request" but less useful. Added the donate button to just below the "share this request" button. Moved the "what is open data" blurb to above stories, and made it plus the stories themselves full width. On small screens the "what is open data" section will disappear - the aim being that on small screen people just want to get something done, and care less about the secondary information.
