### ISSUE TITLE
Account page changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#137]
- [x] Account page doesn't use our colors
- [x] Move big red logout button below the API key
- [x] In sidebar, make clear what API key is for. 
- [x] Have a big CTA for downloading the actual plugins.
- [x] Can we sense what browser they're using, and display only the relevant plug-ins?
- [x] Upon first login, can we send them to a specialized "account set up (username/usertype)", "download" page, then a "tutorial / instructions" page then their account page (which is closer to how it is now). I assume this is possible just by change the links to the initial download page?

**Comment by JosephMcArthur** [comment]
Assigned to myself while I work on what they should be.

**Comment by chealsye** [comment]
I could change the colors on the page, but cannot find the correct page in github...

But the other tasks I don't know how to complete.

**Comment by markmacgillivray** [comment]
@JosephMcArthur the account page does use the colours on the top nav, e.g. the logo, but not in the rest of the page. The content there is just generic so far, there is not anything that specifically needs a branded colour, it is just informational. It doesn't strike me as being highly incongruous to the rest of either site when browsing onto the account page though, which is why it was kept quite plain. As to the first login sending them through a workflow, yes we can, but there is hardly any content for each of those. Presumably you just mean the account setup would have username, profession, and checkbox confirmations, then the download page will just have a big download button (which by the way would bump them out of our "workflow" and onto the download page site), and then they end up on their account page as it currently stands? Is that better? Feels a bit like separating out an otherwise small process just for the sake of it.

**Comment by JosephMcArthur** [comment]
If it's not hard to change the colors, it would be good. 

I think data could be useful here. Mark, can you run the numbers on:
- [ ] What % of people haven't assigned themselves a username and usertype
- [ ] What % of people haven't logged their API key into a plugin
- [ ] What & of people haven't logged a use on the button

You're right, it is a small process but one we've had a lot of complaints about (obviously not ideal). 

We could just try and rethink the account page a bit so that even as a one step thing it makes a bit more sense. For example, having the page be more response. Ideas could be
* Hiding the "Your stories for requiring access to articles and data" section if they don't have any usage yet. 
* Expanding the instructions area on that page and emailing them to a user.

**Comment by markmacgillivray** [comment]
New changes to the account page during signup: 

If a new user, they are taken through the steps of giving us info like username etc, then prodded to download the plugin, then given instructions, then shown their lists of stories and requests once they have any. 

We will know whether or not they have downloaded it (well, we know they clicked the link to go and get it, at least, and later we can check for users who have never submitted anything with it).

As long as they have not submitted a block story or request yet, they will see the getting started instructions telling them what to do. Once they have submitted, they see their lists.

**Comment by JosephMcArthur** [comment]
Mark, can I see / test this before it goes live. One thing I've also just noticed is that 

- [ ] Login page offers you chance to put in security code, but no code is sent. Either remove box for code or send the code ;)

**Comment by markmacgillivray** [comment]
Yep I've got some more changes to finish, I'll add the security code, then
show you on dev. Got a flight today too though, so may be later today

**Comment by markmacgillivray** [comment]
@JosephMcArthur go to test.cottagelabs.com/login and create a new account with an email address that you have not already used on our test system. This will take you through the login process "workflow". Let me know if you are happy with it and then I will make it live. (as mentioned it could do with some nice supporting graphics but those can be added later)

**Comment by JosephMcArthur** [comment]
@chealsye can you look? We need copy edits on this, but it feels much much better. It's still fast. 

@markmacgillivray this feels good broadly, but may need to make some minor changes and what not. Where to download wasn't 100% clear (it offered chrome on only one page). 

Anyway, this isn't all the feedback I have but it's all the time I have right now. Generally, better. Not quite ready for live yet.

**Comment by markmacgillivray** [comment]
Yes it only shows you the link to the version matching the browser you are
using.

**Comment by JosephMcArthur** [comment]
Wonderful.

**Comment by chealsye** [comment]
@JosephMcArthur Is this the same copy as #136 ?

**Comment by JosephMcArthur** [comment]
Think so, the steps are just broken down a bit. We can make copy at each
stage nicer.

**Comment by markmacgillivray** [comment]
This is done.
