### ISSUE TITLE
Homepage adjustments

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#140]
- [x] #138
- [x] reduce number of buttons (don't need api docs for e.g)
- [x] fix attribution on quotes. On small screens they come out of alignment
- [x] Make first button an ask to download
- [x] Give buttons mouseover action
- [x] #136 needs a download action at the bottom.

**Comment by chealsye** [comment]
@JosephMcArthur What do you mean by "fix attribution on quotes"? Is it a formatting issue? I believe the quote attribution to each person is correct.

I don't know how to give buttons mouseover action (change colour when hovered?) -- think @markmacgillivray may need to take that. Also, I removed the API docs button, but that makes two buttons in a three column space. It moved the second button into the middle... looks very off. I'm not sure within the code what's the best way to either centered the buttons or space them better. I enlarged the buttons slightly, but I don't know how to make them larger. I think they're confined to this size based on the the columns.

**Comment by GrantRVD** [comment]
What's the build command we should be using to test modifications to the site format or functionality? @JosephMcArthur kindly pointed me to a related repo which suggests meteor is the builder used. I have meteor installed, but it's not detecting the meteor configuration in this project - I notice that `.cfg` is in the ignore file, so perhaps I just need to create a local meteor project and that'll take care of the problem.

Regarding the milestones @chealsye mentioned:  bootstrap contains several classes for actions, if I recall correctly, including color changes and button movement, so the easiest route there is probably for us just to pick one that's desirable. To fix the spacing of the buttons, there are two solutions I can think of. First, change the class of the button (or their containing elements) to one of bootstraps wider columns. I don't know which piece of code you're looking at specifically, but I imagine it's currently `col-md-4` or something similar at the moment. If so, changing it to `col-md-6` should give you two columns, and hopefully adjust the button size appropriately. The second, more kludgey way is just to have an empty div with the same classes in between the elements containing the buttons.

**Comment by JosephMcArthur** [comment]
@markmacgillivray for the first paragraph above.

**Comment by markmacgillivray** [comment]
The website is not meteor, and has no build command. It is just static file content served by javascript requests to the server. To test locally all you have to do is configure your web server to serve the folder. But you can also just commit to develop and see the changes on the test site, without having to configure anything locally at all.

The site content repos are:

https://github.com/oabutton/oab_static
https://github.com/oabutton/odb_static

The structure of content is just the top-level index.html file, for example in oab_static:

https://github.com/OAButton/oab_static/blob/master/index.html

Which does the usual html links to js/css files etc, such as the main css file:

https://github.com/OAButton/oab_static/blob/master/static/oabutton.css

So, for neatness, static content like js and css files, and images, should go in the /static folder.

And then the content of individual pages just goes in the /content folder. 

I think this info used to be in the README, but that seems to have been overwritten on the oab_static repo. However it is still on the odb_static one:

https://github.com/OAButton/odb_static/blob/master/README.md

**Comment by GrantRVD** [comment]
Thanks for the clarification, @markmacgillivray. It now makes a lot more sense, knowing that the content is actually in a separate repo I previously didn't know about. Some of the changes I'm adding a simple CSS additions, while others require changes HTML files, and I notice at least several of the files in the static directories are the same between this repo and the other two you linked. Which repo should I submit which changes to?
cc @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Reasonably sure it's the other repos.

**Comment by JosephMcArthur** [comment]
@GrantRVD how're you doing here?
