### ISSUE TITLE
Increase site speed

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#143]
- [x] The following publicly cacheable, compressible resources should have a "Vary: Accept-Encoding" header:
https://openaccessbutton.org/
https://openaccessbutton.org/content/index
https://openaccessbutton.org/footer.html
https://openaccessbutton.org/header.html
https://openaccessbutton.org/static/oab.css
https://openaccessbutton.org/static/oabutton.css
https://openaccessbutton.org/static/oabutton_mobile.css

- [x] The following cacheable resources have a short freshness lifetime. Specify an expiration at least one week in the future for the following resources:
https://openaccessbutton.org/static/button.png
https://openaccessbutton.org/static/mountain.jpg
https://openaccessbutton.org/static/oabutton.css
https://openaccessbutton.org/static/oabutton_logo_final200.png
https://openaccessbutton.org/static/oabutton_mobile.css
https://openaccessbutton.org/static/progress.png
https://openaccessbutton.org/static/research.png
https://www.google-analytics.com/analytics.js
https://fonts.googleapis.com/css?family=Raleway
https://licensebuttons.net/l/by/4.0/88x31.png

- [x] Remove the following redirect chain if possible:
https://i.creativecommons.org/l/by/4.0/88x31.png
https://licensebuttons.net/l/by/4.0/88x31.png
- [ ] Remove the following redirect chain if possible:
http://www.openaccessbutton.org/
https://openaccessbutton.org/

- [ ] There are 8 JavaScript files served from static.cottagelabs.com. They should be combined into as few files as possible.
https://static.cottagelabs.com/bootstrap-3.0.3/js/bootstrap.min.js
https://static.cottagelabs.com/d3/d3.v3.min.js
https://static.cottagelabs.com/d3/topojson.v1.min.js
https://static.cottagelabs.com/getter/getter.min.js
https://static.cottagelabs.com/holder/jquery.holder.min.js
https://static.cottagelabs.com/jquery-1.10.2.min.js
https://static.cottagelabs.com/loginstate.min.js
https://static.cottagelabs.com/marked.min.js

- [ ] Reduce image sizes
- [ ] Bootstrap file takes almost 2 seconds to load, can this be reduced? 
- [ ] What does "glyphicons-halflings-regular.woff" do?

**Comment by markmacgillivray** [comment]
Points 1 and 2 done (for OAB and ODB). The creativecommons redirect chain is served by them not us, but could be avoided by changing the URL to their images that is in the content, in the top level index file. The redirect from www to non-www is needed and was added at your request to catch people going to the wrong place, so cannot be got rid of unless you want to lose that functionality. The 8 js files could be contained in one file, but for now I am not making that change. I am considering some wider changes to how the files are served, and at that point will consider this. Reducing image sizes is a content question, just alter them and save into the repo, and it will work. The bootstrap issue must have been an unrelated fault, for me it loads in under 0.2s in multiple tries. The glyphicons file is called by the bootstrap css, it is a standard thing in bootstrap css. Overall I have not been seeing site slowness issues actually, and my testing whilst making these changes saw the load speed go down but only from 1.35s to about 1s. I don't think we really need to be spending time worrying about site speed at the moment.
