### ISSUE TITLE
Tidy repos

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#144]
- [x] How can we make clear a lot of code lives in CL Repo's? Can that just be moved here? 
- [x] Move dev notes from the pad to the wiki here
- [x] Label issues 
- [x] Retire old repos
- [x] Close out of date issues & milestones
- [x] Moved old issues

**Comment by markmacgillivray** [comment]
Code can't just be moved. Having a fork here is possible, but given that is not what gets deployed it would make even less sense to have one sitting here doing nothing. The code that needs to be here is here though, so I think we are OK on this point. If someone wants to contribute to the API stuff, they would prob make their own fork and submit a pull request anyway, so again little point having a copy here just for the sake of showing it here.

What dev notes do you want moved? I don't think there are any that are still relevant. The pad holds meeting notes, but then things from that should go into milestones. We don't use the pad as informative to the code, so there would not be much of use to put in the wiki.

I think this can be closed, but re-open if you want more done.

**Comment by JosephMcArthur** [comment]
What does this repo's code actually do now? I think if we can't move the code at least working to signal where that code is via the read me here (which is sort of starting to become the landing point for the project on github) would be good. Similarly, adding readme's to the relevant places in the CL repo would be useful. If we can't move the code making it more transparent would be helpful - even I can't follow. 

Once that happens I'm happy to close.

**Comment by markmacgillivray** [comment]
Deleted all code from the backend repo and updated the README to point to CL API and separate repos for ODB and OAB frontends, as well as the plugins they already linked to, and the new plugin for when it is ready. Closing again, re-open if necessary.
