### ISSUE TITLE
Utilize awesome twitter stuff on site

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#145]
For example, like we do on SPARC homepage: http://sparcopen.org/. Could this be social proof on the homepage?

**Comment by markmacgillivray** [comment]
Can you give more detail on what you want? I am starting to think about how to provide more info / indication of activity on the site, and this could be useful. The sparcopen page has a panel that shows peoples tweets about open access. Is that what you mean? If so, what would be the twitter content you think would be relevant to display for OAB?

**Comment by markmacgillivray** [comment]
No urgency on this by the way, just going through all the issues.

**Comment by JosephMcArthur** [comment]
Perhaps it could take tweets of folks who found what they needed, can we make an account that would feed this with favourites or something like that?

**Comment by JosephMcArthur** [comment]
Given we want less & less on the homepage, seems like having this on the blog is fine.
