### ISSUE TITLE
Blog updates

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#146]
- [ ] Title bigger on landing page
- [ ] Split the landing page for the blog. 9/12 blog, 3/13 twitter feed?
- [x] Ensure all blogs have an excerpt (@chealsye)
- [ ] Increase font size on the blog, make the width narrower (to increase readability). E.g https://medium.com/art-marketing/meet-the-men-keeping-the-typewriter-alive-in-india-6c8191963aaf#.a9ihnrb0v

**Comment by chealsye** [comment]
Excerpts added to all blogs now

**Comment by GrantRVD** [comment]
I can make the remaining changes here pretty easily on the generated pages, but I need a bit more info about the website/app generator. I asked about this on #140 and will probably get a response there, but just noting for this particular issue that I need to know which files and templates are used to generate the blog page.

**Comment by JosephMcArthur** [comment]
@GrantRVD can you update here too?
