### ISSUE TITLE
Blur location before display on map and in data accessible via API

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#151]
_From @JosephMcArthur on February 19, 2016 10:53_

@Steven-Eardley is passing the location data precisely - so the API needs to blur it. 

_Copied from original issue: OAButton/odb#16_

**Comment by markmacgillivray** [comment]
The API does not, but the map is not accurate enough to view precise locations. It would be possible for someone using the API to get the precise locations out though. @JosephMcArthur do you want the data we store (and therefore subsequently share via the API) to be fuzzified as soon as we receive it, instead?

**Comment by JosephMcArthur** [comment]
Yes. Can we fuzzify everything that can be accessed via the api or map
(from this point on and everything we've got thus far). My only hesitation
here is that very precise locations could be helpful for us to tie requests
to different universities.

Historically we've done this to one or two decimal places I think, so you
can't tell much more than which city it's coming from. Issues in old repos
will have this info.

**Comment by JosephMcArthur** [comment]
@markmacgillivray was the above clear? To be clear reclassing this a bug and retitling.

**Comment by markmacgillivray** [comment]
todo

**Comment by markmacgillivray** [comment]
Added to API now, so future request will be round to 3. Also whenever old data is imported it will be rounded to 3 as well.

**Comment by markmacgillivray** [comment]
http://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude
