### ISSUE TITLE
Will ODB know the difference between someone who's email we have via a request page and or via download?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#152]
_From @JosephMcArthur on February 19, 2016 10:52_

_Copied from original issue: OAButton/odb#15_

**Comment by JosephMcArthur** [comment]
Discussed with Mark. We'll had a tag to show where you signed up

**Comment by JosephMcArthur** [comment]
_From @markmacgillivray on March 3, 2016 12:35_

It knows if the block story supporting the request came from the web page or the plugin, but not whether a user signed up via the site or via the plugin. Is that enough?

**Comment by JosephMcArthur** [comment]
It's okay if we don't know if a user signed up via the pluggin or website.

What I need to know is if they originally signed up via a request page or
via a download page. With the later, we can assume they will then download
and use ODB. However, with the former, that assumption probably does hold -
but we want to push them too. So, it would be good to know the difference.

On 3 March 2016 at 07:35, markmacgillivray <notifications@github.com> wrote:

> It knows if the block story supporting the request came from the web page
> or the plugin, but not whether a user signed up via the site or via the
> plugin. Is that enough?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/odb/issues/15#issuecomment-191745270>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by markmacgillivray** [comment]
New changes to the account page during signup have made this irrelevant now. If a new user, whether via coming to download or via wanting to support a request, they are taken through the steps of giving us info like username etc, then prodded to download the plugin, then given instructions, then shown their lists of stories and requests once they have any. So either way we lead them through the steps to get the button, and we know whether or not they have downloaded it (well, we know they clicked the link to go and get it, at least, and later we can check for users who have never submitted anything with it).

**Comment by JosephMcArthur** [comment]
Will we dump them back on the request page they were trying to support after sign up?
