### ISSUE TITLE
Code testing bots

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#165]
Would it be useful to install Travis / Code Climate or other little thingys (for lack of a better word) in the repos? We used to have them and they seem like a staple in many repos for other projects.

**Comment by markmacgillivray** [comment]
This may or may not be useful for the plugin code repos, that is up to @Steven-Eardley 

For the CL API, automated testing does run to some extent during development, and we do use auto-deployment via codeship which tests the builds before they are deployed. There is nothing on the repo indicating this though. Over Summer we are focussing on developing the CL API testing infrastructure further. We could put those little logos on, perhaps, depending what test infrastructure we use - but having them or not does not actually indicate that tests are running or not, or that the code works or not; it is not uncommon to see build:failing on certain branches of code repos, particularly the master branch, whilst not really being an indication of the state of the code. They are fairly gimmicky, but could be useful, depending what infrastructure we decide to use in the end. The main point is to use what is most useful for the way our team works, not whatever is most common or most fashionable.

**Comment by markmacgillivray** [comment]
For the CL API, I have just added a codeship badge to the README, which indicates if our builds and deployments are passing.

**Comment by JosephMcArthur** [comment]
What to do here is totally in you and @Steven-Eardley hands, I don't know enough about it.

I had a feeling you probably already did automated testing during development. I'm more than happy to buy anything here if needed too or take a while to set things up myself on the repos (would probably aid the understanding). 

Where it's easy to add badges I expect it would contribute towards #166.

**Comment by markmacgillivray** [comment]
Assigned this one to @Steven-Eardley now so he can let us know if he needs any code testing bots etc for the extension repo. It won't need deployment, and maybe automated tests is not so useful either, but waiting to check with him. If not, we can probably close, now that we have a badge on the CL API repo, which does make more use of these features.

**Comment by Steven-Eardley** [comment]
I've been rather lax in putting unit tests in the extension thus far - I'd be happy to add some (e.g. for essential transactions with the API - but care will need to be taken that these are discarded). It might help the ongoing development work as keeping extension and API in a compatible state with each other is paramount. I'll open a unit tests issue on the extension repo.

**Comment by markmacgillivray** [comment]
@Steven-Eardley the backend now automatically hides any blocks or requests with a key called test and the value true. So you can create ones with that value during tests, on either the dev or live API, and it wouldn't disturb what users see. Also it now only accepts one block per URL per user so you'd have to take that into account when trying to create test records. I think you can also delete cos the API if you wanted to clean up afterwards - if not, I can easily enable deletion if you need it.
