### ISSUE TITLE
Nav bar for OAB site changes depending on if you're on /login or other pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#180]
Thought for quite a while I was going insane here, but it does change. 

On login there are missing headers and the font weight is different.

**Comment by markmacgillivray** [comment]
Yes, could be since the static site pages were updated - the logged in
areas are separately controlled at the moment.

**Comment by JosephMcArthur** [comment]
Thought as much. Assigned to you. I'd suggest:

- [ ] Style from login page
- [ ] Headers from static pages

We should document this somewhere:

- [ ] Add a note about this in static repos (anywhere, I'm overhauling in #160 )

**Comment by markmacgillivray** [comment]
Sure, will fix. The fact that they're separate should change in near future.

**Comment by JosephMcArthur** [comment]
Depending on how near the near future is, I'm happy to wait if it saves a few minutes. Just boot up another issue for merging those systems and tag this there.

**Comment by JosephMcArthur** [comment]
No longer happening on dev site.
