### ISSUE TITLE
Change SEO settings to give better links via google search

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#183]
These aren't the most important things to have people click/know from search.

Should change.

<img width="602" alt="screenshot 2016-07-19 17 53 38" src="https://cloud.githubusercontent.com/assets/4953703/16958750/cd463f8e-4dd9-11e6-97e6-168cba4ce0a6.png">

**Comment by JosephMcArthur** [comment]
@markmacgillivray first step here is to know how these are generated currently.

**Comment by markmacgillivray** [comment]
Turns out they are automatically generated by google, and we cannot control them. They are what google think is most useful for visitors.

The ones it shows now seem pretty useful, no?

I think this can be closed now, but will leave open and assign to @JosephMcArthur for final decision

**Comment by JosephMcArthur** [comment]
3/6 pages I currently wouldn't want shown (support, /request/new, /advocacy). I swear there is a metadata schema for this that you can provide in the site map (or something like that). But, if you've looked & we can't change them then please close.

**Comment by markmacgillivray** [comment]
I thought so too, but according to google dev docs, nope.

**Comment by JosephMcArthur** [comment]
¯\_(ツ)_/¯

**Comment by JosephMcArthur** [comment]
On /advocacy & /support can we tell google not to look at the page (norobots?)
