### ISSUE TITLE
Pages to filter out

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#187]
- [ ] Twitter.com
- [ ] chrome://history/
- [ ] dropbox.com
- [ ] mail.google.com
- [ ] netflix.com
- [ ] google.com/maps
- [ ] youtube.com
- [ ] calendar.google.com
- [ ] addons.mozilla.org
- [ ] history.com
- [ ] bbc.co.uk
- [ ] google.com

Can these be stored on a list which the plug-in could pull from too? For example, to serve a "this doesn't look like an article" type thing.

**Comment by JosephMcArthur** [comment]
Also, can I suggest we keep this as a running issue and just plonk sites here as needed?

**Comment by markmacgillivray** [comment]
Moving to next milestone, keep as running issue, some of these are already in, will add more, and make an admin area addition where they can be managed

**Comment by markmacgillivray** [comment]
Moving

**Comment by JosephMcArthur** [comment]
Am seeing things like gmail on /request still, can we get an update?

**Comment by markmacgillivray** [comment]
The requests that are there are not fully filtered yet. I still have issues loading all the old records. It is not the main concern just now though, as per previous emails about loading data

**Comment by markmacgillivray** [comment]
The filter is in place now. Can we close this issue? I think it would be good to start a google spreadsheet that has the URLs we want to filter, then later I can add an auto-call that will update the blacklist from the spreadsheet. Re-open if necessary.

**Comment by JosephMcArthur** [comment]
Happy to close, have added a follow-on issue at #288
