### ISSUE TITLE
Stories, blocks, requests, oh my

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/backend#188]
We have too many concepts.

Originally, the OAB recorded the fact that people were blocked when trying to access an article. This was good - it allowed exposure of a problem that led to advancement of the OAB project and also of access to academic material in itself. Then we thought it would be good to extend that by having stories about why people wanted to get round blocks so they could do something useful. This was a good idea at the time, and a useful intermediary step. Then, we also came up with the idea of requests - this is a really good idea, and is a niche that is really needed.

Blocks and stories are no longer so useful on their own, because we know people can now get access anyway - not necessarily legally, but the knowledge of how to find content has spread much more widely than it was when we started. The focus now, therefore, is on requesting access in order to change how the authors behave, and in order to allow for institutional (legal) access.

So what does this mean for blocks, stories, and requests?

It is still useful to know that a user has been blocked on a particular page - e.g. that they hit the button on some URL, for presumably the reason of being blocked (or occasionally just because they wanted to see what the button does). But stories about blocks are not that useful - blocks themselves are no longer the contentious point of action. Requests, though, are still very useful and are supportable by stories.

The problem is though that new users (and probably many old users) don't know what blocks are  - they no longer serve a clear purpose, so it is hard to understand them. This makes it less clear what the purpose of a story is, and this in turn makes it hard to understand how a story - and collection of stories - support a request.

So, in order to focus on requests, we should drop the concepts of blocks and stories.

Note - we should still keep tracking blocks, but it should just be a useful aggregate number. And we should still keep collecting stories, but it should be clear that they are for supporting requests, not blocks. So stories are just part of requests, either directly the first story that triggers the request, or a story in support of a request, and they should appear in the UI on the request page - not separately.

Also, because what we now want to do is to generate requests to authors to get content made publicly and legally available, what we really need to do is make it clear to our button users that what they are doing when using the button is starting the process of a request. Of course, in the case where we already have the content they want, the interaction is short and we just tell them it is already available and point them at it. But where it is not, we should provide the shortest route to them starting a request - which is NOT actually the same as the shortest route to getting content or making a statement about being blocked.

Because of this, we should change how the button works:

* record that the user clicked the button on a given URL
* return any content we have for that URL
* return any open requests we already have for that URL
* ask the user to check boxes indicating what sort of content they want, and that we do not already have (dynamic list depending on what services we are offering - articles, data, ...)
* ask the user to explain why they want access
* let the user submit their new request, or add their story to a relevant open request
* confirm request creation and inform user of links to the request page
* ask the user to get involved with the request - go to the page and check metadata info
* follow up with an email to the user thanking them on starting their request (or adding support to it) and again ask them to go to the request page to confirm details about it
* in the email, confirm the request metadata we do hold and ASK the user to fix / supply any that is incorrect / missing
* email requesters / supporters whenever content is received, or request status changed
* email requesters / supporters weekly with a digest of their request statuses (which they can also get to via their account UI)

This DOES make the button itself less immediate, but ONLY in exactly the case where we want to get people more involved - e.g. where we want them to get involved in a request.

Request metadata will be auto-extracted where possible without intervention from the user. But, if it is incorrect and the user wants to fix it on the request page, it is only as hard as them clicking a link on the request page to re-open the URL in question, and confirm stuff. In their confirmation email, we can easily let them review the metadata we did extract, so they know if it is worth going to check it in the first place. We could also send further nudge emails for say 3 days after submission asking for specific bits of missing metadata for a given URL.

I think this would allow us to make it clearer to users what the function of the button is, and why they are using it, and what it is doing for them - and it keeps the concepts simple, as requests. It would also engage the user more in the function we now intend to provide.

This would also make the button simpler to use and maintain, and would make it easier to embed similar functionality direct into web pages where desired, and to easily add further methods of getting content to a dropdown list on the button, such as ILLs

One final, perhaps more contentious point - to keep this conceptually and technically simple, this should just be one button, one service, for getting access to STUFF, whatever the stuff is. We should not continue supporting multiple buttons and multiple sites for different kinds of stuff. With good use of graphics / icons / imagery we can make it clear what kinds of stuff we have requests about, and again can more easily extend the concept to other kinds of stuff in the future, and to other sorts of request.

@JosephMcArthur @Steven-Eardley this is our most critical decision at present, I think.

**Comment by markmacgillivray** [comment]
On discussing this, we have agreed essentially the above. There was a change to include the email address in the information we collect from the user in the button on the page, as it seemed to make sense that that is the one place we really need content to progress with, and the user may be better placed to gather it than we can. However, I have since reviewed the ODB content to date, and think this idea has to change.

We have 499 blocks registered on ODB since it opened, and only 6 requests. This indicates first that getting from blocks to requests is too hard, and needs to be simplified. 

It would still make sense to collect the email addresses in the new plugin, BUT it also turns out that of the 6 requests we do have, only 2 of them could possibly have retrieved the email address from the page itself - the other 4 do not contain author emails at all, not in the displayed UI, nor in the source code, nor in the pages linked about the authors. This means that the users must have been going off-button anyway, and googling the authors to try and find email addresses for them. Following this logic and trying it myself, indeed I do find 3 email addresses quickly this way, and I find that in the 4th case the user has put in one of their own email addresses rather than that of an author - the user could just have been testing, but it is real content, so perhaps another indication of the user not understanding what to do.

Of the 2 requests for which we do have email addresses, we could certainly have extracted them ourselves anyway - in one case extremely trivially, and in the other, slightly less trivially but still with ease. Where this is the case, and particularly if users in most cases are not even seeing email addresses to provide in the page they are on, it makes better sense not to impede the process of the user creating a request.

This does indicate though that we will NOT be able to extract email addresses ourselves from pages either, in the majority of cases - because they are not even there.

However, I think that in this case it is even more important to let the user feel confident about what they have done - that is, created a request. Then we get them into that whole process, email them about it, link them to their request page, show there the metadata we have managed to extract, and give them the opportunity to go on their own wee data safari and come back to the request page with the email addresses they are able to find - as noted, those that care must be doing this anyway, and in the case of those that do not have time to do it, if we can get to the stage of creating requests then we have greater chance of other people being interested, supporting them, and providing the necessary missing info.

So @JosephMcArthur - back to proposing we only accept the user story on the button! (but this time based on what we have gathered so far, rather than just initial assumptions)

**Comment by JosephMcArthur** [comment]
Thanks again, Mark. My concerns here are:

* Sample size
* We know there are issues in making it through the plugin and inputting
emails currently.
* We haven't asked people who've registered blocks why they haven't made
requests.

and so I'd suggest essentially the same course of action as before.
Although, I'd suggest we also:

* Ask everyone who made a block, but not a request, why.
* turned all blocks into requests after the new release (including running
a email scrapping function on them). Blocks will stop existing, and we'll
start a request at the point we know what they want and why*.
* give requests have an "email needed" status. This would be the equivalent
of a block, but is far more actionable.
* Examine the success of getting emails automatically vs the plugin vs
email vs the community vs internally in the new release and make a decision
on if we can simplify from there. We can give the user a "I can't find the
email now" button in the plugin which they can use to close it.

Again, appreciate you looking at this. If the technical burden to keep
emails in the plugin is higher than we've discussed (i.e pretty easy) then
I'm happy to keep considering dropping it.

**Comment by markmacgillivray** [comment]
It's not a technical problem to get emails, it was just Steve and I
thinking of the user workflow. Although I do agree about the sample size. I
think I'll run a scrape on every URL we have a block for, and find out how
many have email addresses at all. Then we can get an idea if we're likely
to have users finding emails or not.

**Comment by markmacgillivray** [comment]
Continuing in next sprint

**Comment by JosephMcArthur** [comment]
@markmacgillivray, I'm happy to close this. If you're not, please reopen.
