### ISSUE TITLE
Change sign up to include Name & Affiliation. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#199]
For data requests, some more information on who's requesting will be useful for Authors. We may consider adding in folks Full Name and Affiliation at sign up. We might also want to add industry to our dropdown list of user types.

**Comment by JosephMcArthur** [comment]
Could still keep people's usernames as what is displayed on the site - and only use full name for emails to authors. 

Could we also add a ORCID ID to sign up?

**Comment by chealsye** [comment]
I think this is a great move if it is optional. We can ask existing users to strengthen their requests and/or user profile by providing their full name and institutional affiliation. Going forward make it option fields with registration. I think most users will be fine with this. Some may not be and it's good to allow them the continued option of basic username. Using ORCiD is a fantastic idea. Will make it easier for users who already have an ORCiD. Is it difficult to grab the user info using ORCiD?

**Comment by markmacgillivray** [comment]
These fields have been added to the new signup page, although it will not grab info automatically if people provide an orcid - this could be done, but users have control of how much info they can make public on orcid, and not many people have it yet, so there is not sufficient coverage to make it worth querying. Later we can add this if we see many more people using it though.
