### ISSUE TITLE
Sign in page is not obviously also a sign up page

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/backend#209]
Change text to make it clear the user can sign in OR sign up, immediately. Get rid of the small print, make it more obvious. This is on the /account page when not logged in.

**Comment by JosephMcArthur** [comment]
You've seen the copy changes for this right?

sent from my phone, please excuse any typos.

**Comment by markmacgillivray** [comment]
Somewhere yes. But also a note to remind me of the particular issue Steve
has with it, for making it obvious for people signing up when installing
the plugin.

Mark

**Comment by markmacgillivray** [comment]
New site style fixes this
