### ISSUE TITLE
Combine ODB and OAB resources pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#213]

**Comment by JosephMcArthur** [comment]
Responding to @chealsye's blocked comment on teamsnippet & doing structural HTML work here. @chealsye that should mean you only need to worry about copy here. 

@markmacgillivray we've spoken about filtering for data vs articles on this page. What would be useful to add to the code to set the scene for implementing this later? You mentioned adding classes?

**Comment by markmacgillivray** [comment]
Yes for things relevant to data you could wrap them in an element with a
class called data. Same for article stuff, but use a class called article.

Some of the old code on this sort of page, and on the about page, could do
with improving. It could be simpler. However for now if you want to proceed
with copy, then yeah just wrap in classed elements.

**Comment by JosephMcArthur** [comment]
Would that be:
` <div class = "data">
CARD CODE AS NORMAL
</div>
`

The about / support pages code is so complex & fragile. Perhaps when launches are all over we can refactor those pages & do this page while we're at it. 

While not critical, it does keep our code base editable, enable contributions & save time in the long run which is good. I'll start an issue for it.

**Comment by markmacgillivray** [comment]
Yes, although no spaces around the equals sign. Also it can be a div but
doesn't have to be. So if there's specific paragraphs, links, or whatever,
anything that is an element can have a class attribute added to it, and if
data or article is one of the class attributes then it'll work.

**Comment by JosephMcArthur** [comment]
@markmacgillivray I have a pull request so you can check my code. 

https://github.com/OAButton/oab_static/pulls

**Comment by JosephMcArthur** [comment]
@chealsye this pages structure is now merged & live at http://oab.test.cottagelabs.com/resources. I made the odd copy change, but nothing decent - leaving that with you.

**Comment by JosephMcArthur** [comment]
I've just made enough changes here so that it doesn't block release. @chealsye checking them to make sure you're happy would be great but if you can't invest time at this stage this is not longer blocking us and you can invest elsewhere. 

Close when you're happy.

**Comment by chealsye** [comment]
It's fine for now. Two of the boxes aren't colored right or there's an empty space - not a big deal though. But the content is fine. They've been brought together. But a redesign of the resources page may want to be considered in the future.
