### ISSUE TITLE
Quickly condensable things in the footer

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#216]
- [ ] Team Button doesn't need to be in the footer (we're retiring it as request pages are doing that faster than ever expected)
- [ ] Legal can leave the footer and go in about us (or under contact). To close, remove from issue and leave big note in about page. 
- [ ] Code statement can be moved to same line as CC-BY statement. So it could read "This work is licensed [licence image]. Our code is open source and on [github symbox]. Want to help?" then link to support. 
- [ ] Contact us can go under about us and be removed from footer
- [ ] Press can be removed from the footer

**Comment by markmacgillivray** [comment]
Done, slightly differently to aid layout on small screens.
