### ISSUE TITLE
Changing story prompt to give better stories

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#217]
From @chealsye  

"The prompt: "Tell your story - why were you blocked? What were you trying 
to do at the time?" 

SO many stories are just saying "trying to access x." A different prompt 
could generate more real stories about why they need access. I'll have a 
think, but wanted to flag it when it came to mind."

@chealsye have you had any other thoughts on this?

**Comment by markmacgillivray** [comment]
I added "Why do you need access to this content? Please tell us your story! We'll share this with the author, so a good story will convince them why they should share their work!" to the current development, at http://oabe.test.cottagelabs.com/html/main.html. But any other suggestions welcome!

**Comment by JosephMcArthur** [comment]
I think we need to be more concise. The reason it's structured this way
currently is to narrow down the types of responses we get. We could
structure the input box to make this more obvious, or try other ways of
doing this. For data requests, it's likely that we need to give people more
space to ask these questions.

We've had to think a lot about these sorts of questions for OpenCon, I
wonder if we could pull in some expertise there.

**Comment by markmacgillivray** [comment]
Yes I agree we need to be more concise. I just added text to get the thought of being more convincing across. The other texts on the plugin demo, as discussed yesterday, will be changed to visual imagery. But we still need to say something in the text box, hence yeah any further suggestions welcome.

**Comment by JosephMcArthur** [comment]
Mark, can you pull a list of all stories please and send it as a CSV? I
want to take a look and send it over to folks to see if we can find a
better prompt.

**Comment by markmacgillivray** [comment]
[stories.txt](https://github.com/OAButton/backend/files/444674/stories.txt)

**Comment by markmacgillivray** [comment]
there are about 6300 stories in the above text (csv) file. I have filtered out ones that are already marked as test, but there could well be some in there that are still gibberish. Another clean of the stories will take place when we move to the new system. But that collection should be pretty good for getting an indication.

**Comment by JosephMcArthur** [comment]
# Major update

## Background

Current prompts: 
![screenshot 2016-08-31 11 14 59](https://cloud.githubusercontent.com/assets/4953703/18124923/3198ab9e-6f6c-11e6-8935-16f468e4fac4.png)

The ideal case here is that a user finishes the sentence, few actually do. It's designed this way to:
1) allows us to merge it smoothly into emails
2) allow us to tweet it
3) allow us to display it on request pages
4) allow us to show it on maps

## Moving Forwards

1 and 3 are now the primary use cases for this statement. Meaning we could make the text box longer if desired. Realistically, we should probably expect to drop the "smooth" merging into emails  unless we're willing to edit stories or ask users to refine them after 1st attempts. If we are willing to do that, we need to create backend tools to make it easier. 

So, the easiest thing to do now is just draft a better prompt, especially for data requests. However, alternative approaches could include:
- Giving people dropdown options of types of answers
- Allowing people to reuse stories they've previously written

**Comment by JosephMcArthur** [comment]
Also, have asked Nicole Allen to help here based on her work doing questions for OpenCon.

**Comment by markmacgillivray** [comment]
Giving dropdown options or allowing people to reuse stories seems like a bad idea to me. If what we expect here is unique information, then it should not be possible to answer with generic messages. If it is, then people are just going to answer with generic messages. If people are just answering that way anyway, we would be better getting rid of the idea of a story altogether and just providing a few options for why they want access.

I think the only way to get better stories is to take people closer to the idea of their request "petition", which we are already doing. The story is now mandatory before the request can be submitted.

I would actually remove the "with this I can" approach altogether, and also would not link out to an explanation of "why" the story is important. If we are collecting the story in the extension, we should say in that box why it is important. Then during moderation of the new request, we should create a status called "story update", and the moderator could set it to that which triggers an email to the user to come back to their request page and improve on the story. Once sufficiently improved, then the moderator can allow the request to progress.

But this only works by engaging the user with the request "petition" page more, rather than just with the button itself. They have to think more about their request page and what it can do for them. As mentioned though, we have already been moving towards driving users in this direction, so we could certainly keep that push going.

**Comment by JosephMcArthur** [comment]
I agree with your actions above Mark, including:

- [ ] I would actually remove the "with this I can" approach altogether
- [ ] do not link out to an explanation of "why" the story is important
- [ ] during moderation of the new request, we should create a status called "story update", and the moderator could set it to that which triggers an email to the user to come back to their request page and improve on the story.

I wonder if we can put in simple ways to nudge people to improve their stories. I have a couple of hypothesis:

1 One word stories aren't sendable
2 Longer stories are generally better
3 Including the word paywall or open access aren't sendable
4 stories including the word testing / test aren't sendable

These are all fairly easy to test, and I've just put together a doc for that: https://docs.google.com/spreadsheets/d/1vLiIwVwAEnTDKKsx0OFQwQX8O5T06DbLPY7xzD2vLqQ/edit#gid=0. 

Mark, could we add checks and nudges in to catch these (soon, or eventually). E.g, for each we could:

1) reject stories without spaces and send back advice on good stories
2) give folks a "strength bar" like folks do for passwords based simply off length 
3) reject stories with this word and send back advice on good stories
4) reject stories with this word and send back advice on good stories

**Comment by markmacgillivray** [comment]
We could reject some words, but that is very tricky. e.g. we cannot reject the word "test" - some people will be wanting access to run tests with the content, science experiments are tests! So perhaps better not to reject words. But the strength bar idea is good, and can be augmented over time, so we could start with basing just on length then add or subtract score based on words used, so rather than rejecting on the word "test" or "open access" we may score them down a little bit.

**Comment by JosephMcArthur** [comment]
Maybe I'd change my wording of reject to "flag". So, for instance, if the word paywall is in there we could show something when they submit the 1st time like:

"We find stories with the word paywall don't work. You might instead think about:
- Story tip one
- Story tip two
- etc

However, if you're sure you can just hit submit again!". Then they could either change or do nothing, and we'll accept it. 

I quite like the idea of the bar reacting to these words though. That's worth more thought.

**Comment by JosephMcArthur** [comment]
Mark, for the Stories.txt file, what sort of stuff is in it? Is this recent + old, just recent, just old etc? I think this would be a great thing to ship the next version with (we can debate if it's feasible) and I want to see if there is a pattern in the stories. If there is any systematic bias in the sample you've given, knowing now would be great.

**Comment by markmacgillivray** [comment]
It's everything that has a story of any length more than zero, from new,
old, old old, all we have.

**Comment by JosephMcArthur** [comment]
Great. I now have spilt that dataset into a few parts. 
- All (6400)
- Unique stories (est 4500)
- Duplicate stories (est 1800)

and added tests for the number of words, string length and the occurrence of things like test / paywall. 

The next step would be scoring each story (relatively fast, but not trivial). This should give us a reasonable evidence base to work from in developing this bar. This dataset could do a few other things too. 

That would allow us to test each of these factors against score strength, and we can find things that correlate. 

Mark, in prioritising this, what would be your estimate of the feasibility of adding the "strength bar" before the next release if we give you the basic outline of a model to work from? E.g < 4 words is weak, 5-15 is great, 15+ is bad.

**Comment by chealsye** [comment]
What about simply asking "How would getting access to this research help you?" I think it prompts a more meaningful response than "trying to get access to x" and is concise.

**Comment by markmacgillivray** [comment]
"How would getting access to this research help you?" sounds good.

The getting started instructions that the user sees when they sign up could say "giving a good answer to that question is more likely to convince an author to share the content with us" or something like that. So we tell the users they should do this, but the plugin itself stays concise.

**Comment by markmacgillivray** [comment]
The prompt has been changed in the dev plugin, and a button UI to indicate word length and how good that is has been added

**Comment by JosephMcArthur** [comment]
Current version in designs: How would getting access to this research help you? This message will be sent to the author.

**Comment by chealsye** [comment]
I think the additional of "This message will be sent to the author." is
very helpful. Yes, it makes the prompt longer, but it hopefully will
incentive users to provide a meaningful story.

**Comment by JosephMcArthur** [comment]
This should be on the request pages too, where "will" should probably change to "may". 

@chealsye any luck on finding folks to rate stories?

**Comment by chealsye** [comment]
It's proving harder to expect. I've started reaching out to individuals I
know to get it going.

**Comment by JosephMcArthur** [comment]
Closing this issue for now, as I think we've made good progress on this. To move forwards here I'd suggest:

* @chealsye you keep trying to get things scored
* @meganwaps you get folks to feedback on this prompt specifically during testing

Any feedback we get can be as a new issue.

**Comment by JosephMcArthur** [comment]
Wait, sorry, I don't have confirmation from @markmacgillivray  this is in the new build yet.

**Comment by JosephMcArthur** [comment]
This also needs to be on the new request making page

**Comment by markmacgillivray** [comment]
What does?

**Comment by JosephMcArthur** [comment]
Okay, have added the new prompt to the new request page and new request making page. 

Mark, is the prompt "How would getting access to this research help you? This message will be sent to the author." in the dev plugin?

**Comment by markmacgillivray** [comment]
As far as I know yes. In the story box:

http://oab.test.cottagelabs.com/request/new

**Comment by JosephMcArthur** [comment]
I just added them. I'm just referring to the plugin / bookmarklet now.

**Comment by markmacgillivray** [comment]
I think that was already in that box, I put it in earlier. It is already in the plugin, yes.

**Comment by JosephMcArthur** [comment]
Great, then we're good to close!
