### ISSUE TITLE
confirmation email Issue

### ISSUE THREAD

**Issue by natalianorori** [OAButton/backend#221]
When uploading data to the website, I received not 1 but 24 confirmation emails from admin@openaccessbutton.org, has this happened to anyone else? @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Never happened to me at that scale. This might be linked to #219 .

**Comment by JosephMcArthur** [comment]
Okay, some background on this from what Natalia sent me. 

> When uploading a doc, I press the submit files button and nothing happens. The only thing that assures me my data was uploaded is checking my email and getting the confirmation. Some sort of “ Data Successfully Uploaded” message in the website might be nice

Wondering if it was pressed many times.

**Comment by natalianorori** [comment]
I actually didn't press the button 24 times. I just pressed it once. 

After this happened , I did a second test and uploaded docs again with another test request, this time I pressed the button about three times and got no confirmation email at all.

**Comment by JosephMcArthur** [comment]
@meganwaps can you try and replicate this please?

**Comment by JosephMcArthur** [comment]
from #154 this won't happen now
