### ISSUE TITLE
Deal with FF Corruption 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#231]

**Comment by JosephMcArthur** [comment]
@markmacgillivray we can't seem to find the file for this. cc @meganwaps

**Comment by meganwaps** [comment]
@markmacgillivray @JosephMcArthur any luck finding the FF code?

**Comment by markmacgillivray** [comment]
I talked to Steve about this. The latest firefox version was actually generated from the oab-chromeaddon, which was a port of the old code into a newer-ish chrome framework, but still with the old code inside it. So still the potential for errors from old code becoming invalid in there. The generated file must originally have been created by Steve and uploaded to the FF store by Joe (Steve says he had no access to the stores and just provided the files). However Steve no longer has the file.

@JosephMcArthur does this sound familiar to you, would you have such a file anywhere? If not I can generate a new one once I get the script (I think Steve has linked to it in the repo, just have to look - have not used that stuff yet.)

**Comment by JosephMcArthur** [comment]
I think this is that file: https://www.dropbox.com/s/9azqwhmnka5hesy/odb_firefox_0.8.7.xpi?dl=0

**Comment by JosephMcArthur** [comment]
@markmacgillivray @meganwaps any update on manually installing this? I'm told it's unsigned.

**Comment by JosephMcArthur** [comment]
My suggestion here is that we write a quick note about this on the blog (@chealyse) and link that from the current Firefox button on account / download pages. Or, we can simply remove that button for now.

**Comment by markmacgillivray** [comment]
Presumably it is OK to close this, now we have two weeks to go until new version, and no fix for the old FF. The dev site just shows a msg saying new plugin coming soon.
