### ISSUE TITLE
 Getting Started / Instructions Graphics and/or walkthroughs

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#236]
Need to have some FABULOUS instructions for the new tool. There are several approaches to this which I'll layout in future comments.

**Comment by JosephMcArthur** [comment]
The layout I currently have in mind for this page is below, from dropbox's homepage (when you're not signed in).

<img width="1280" alt="screenshot 2016-09-21 11 42 24" src="https://cloud.githubusercontent.com/assets/4953703/18707991/7aa85b74-7ff0-11e6-9dab-77211eb5d9c3.png">

I image we can use screenshots for the images & just walk folks through step by step. Hopefully, we can also include some "try it" elements. Sits where we'd encourage them to go, open it, and what not. Seems people really want to do this so why don't we let them!

**Comment by chealsye** [comment]
@JosephMcArthur Instructions copy and some graphics are here: https://docs.google.com/document/d/1W9t4uZgPyC6wSSnNvJ7WIRddK2oYAW3rzaivKyzKcjs/edit#

Let me know if this is satisfactory and we can begin putting it up and get this closed.

**Comment by JosephMcArthur** [comment]
okay, spoke with @chealsye. Have decided that really long instructions are helpful but not what we need right now. I have:

* drafted some basic, key info only instructions. I have them at /instructions & on the account page next to the place to download buttons. I have added titles to these sections. @markmacgillivray any visual tweeks you can make & checks you can run here would be appreciated. They should probably _always_ display on that page. 
* I have deleted the old version at /start
