### ISSUE TITLE
Quotes on map difficult to read

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#237]
The quotes over the world map (currently on the test site) are difficult to read. It isn't impossible to read the quotes and attribution, but this should be easy to read for users.

Some possible solutions:
* Outline the text
* Bold the attribution
* Add a bar behind the text (opaque would definitely fix it, but more transparent would look better)
* Fade the colour of the map?
* Reorient the map is also another solution...

Additionally, some letters are slightly cut off on the right side of the slider.

**Comment by JosephMcArthur** [comment]
To add to this, on my screen the 3 dots overlap text on some quotes. 

see: https://www.dropbox.com/s/xs0ces9uunrt7rz/Screenshot%202016-09-19%2015.00.02.png?dl=0

**Comment by chealsye** [comment]
@JosephMcArthur We're not looking at the same thing. No wonder you didn't see a problem! Your screenshot is definitely easy to read with the exception of the dots.
![screen shot 2016-09-19 at 10 02 44 am](https://cloud.githubusercontent.com/assets/9299248/18634725/53a51d60-7e50-11e6-9598-9470ca580003.png)

**Comment by chealsye** [comment]
Vote that we change to the design on Joe's screenshot. It's cleaner and beautiful.

**Comment by JosephMcArthur** [comment]
Lol, yes that's really hard to read. Okay, I think you need to do a hard refresh on the test site: https://wiki.scratch.mit.edu/wiki/Help:Hard_Refresh. That should get your looking at what I'm looking at.

**Comment by chealsye** [comment]
No issue remains with legibility.
