### ISSUE TITLE
Security codes & links doesn't allow login on test

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#238]
On both Chrome & Firefox & Andriod inputting email will often lead to email being sent, but upon trying to use links or code the site tells you that the it's expired.

Verified by @meganwaps. 

The response is quite irregular. When the email is sent, it's fast. However, sometimes when you put in your email it immediately tell you the link has expired from that page. 

#### Discussion on issue so far:

Is the login page now functional on test? 
Mark MacGillivray (mark@cottagelabs.com)
Yes
If editing the content of that page just be careful of the structure and element IDs.
It's the main critical functional page
If you have the dev plugin installed and go to the dev site you should also see it trying to check your api credentials for you automatically.
But if you create new requests with the dev plugin you may not see them anywhere yet
I'm not sure what I have the explore requests page pointing to at the moment
Not sure the dev login page is sending codes yet
Mark MacGillivray (mark@cottagelabs.com)
It was earlier
I'll just sit tight for a while
Mark MacGillivray (mark@cottagelabs.com)
It's weird, every time I test I get the emails within seconds. But when other people try, they get delays!
Unless an earlier dev change has broken it
I think there may be some funky caching
Put my email in on firefox
email arrived
open the link in chrome, and it failed
Can't get it to send links in chrome
Don't worry about this though, deal with our eyes! 
and holiday
We'll touch base next week
Mark MacGillivray (mark@cottagelabs.com)
It's chrome I've been using to test
You'd probably have to use the same browser that you requested the link on
Tried that. I put the link in FF and it didn't seem to do anything
Mark MacGillivray (mark@cottagelabs.com)
Hmm it still works on chrome on my phone
Make an issue about possible not working on FF

First time it's seen this email on this device
Putting my email in via the homepage worked
But the link to login failed
Mark MacGillivray (mark@cottagelabs.com)
If it's chrome it can sync your cookies from your laptop. We could even make it so that you can login on multiple devices this way, but so far I haven't

**Comment by JosephMcArthur** [comment]
May be connected to #252 if that's expected to work. 

More info for the above. I'm on Mac 10.11.6 (15G1004) & Version 53.0.2785.116 (64-bit) for Chrome. Can't get it to work on my phone (Android), FF, or Safari (on a guest account). 

Can @OAButton/team test the system, let us know if they get the same issue, and if so comment in your computer & browser versions. Ideally by the end of the week.

**Comment by markmacgillivray** [comment]
Let me know if you're trying on different chrome devices rather than just
one - I do have it strictly set at the moment to be per device, but
possibly having that check plus that browser capability to share settings
across devices is making it refuse your login sometimes. This can be fixed
easily once we identify just what the issue is. FF has this capability too,
so may be worth someone testing without being signed in to the browser - eg
chrome lets you use it with or without signing in with your Google account,
and if you're not signed in it shouldn't be the problem of cookies across
multiple devices

On 22 Sep 2016 20:38, "Joseph McArthur" <notifications@github.com> wrote:

May be connected to #252 <https://github.com/OAButton/backend/issues/252>
if that's expected to work.

More info for the above. I'm on Mac 10.11.6 (15G1004) & Version
53.0.2785.116 (64-bit) for Chrome. Can't get it to work on my phone
(Android), FF, or Safari (on a guest account).

Can @OAButton/team <https://github.com/orgs/OAButton/teams/team> test the
system, let us know if they get the same issue, and if so comment in your
computer & browser versions. Ideally by the end of the week.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/OAButton/backend/issues/238#issuecomment-248990424>,
or mute
the thread

**Comment by JosephMcArthur** [comment]
Earlier I tried Safari on a guest login on my Mac. That didn't work. I just
tried "Browse as Guest" on Chrome, same versions, also no luck. Tried with
two emails & using the link & code but still no luck. My login has always
expired.

On Firefox, I just cleared my cache, history & entered ingonito. Put in a
fresh email (with a plus in it) and tried to login. The first click told me
my login had expired, I clicked again and it told me it had sent an email
(which didn't arrive). I then used my personal email (no plus) and it sent
me an email. Still couldn't login though. I then got a hunch it doesn't
like pluses. I tried emails with +'s in FF & Chrome. The same response is
seen. I expect we have a bug with +'s being entered. I've certainly tried
using many emails with plus's in during this debugging process - which
can't be helping.

Where there are no plus, the email is reliably sending within a few
seconds, though. That's something!

Joe

**Comment by natalianorori** [comment]
I tried Safari and Chrome on my mac and I couldn't log in either. I got a "Link has expired message" as well. Never got the email.

I logged in from Safari onmy phone and got the email, however when I clicked the link I got the link has expired message as well. 

I used my personal email all the times I tried logging in 

Im on Mac 10.11.1 (15B42) Version 9.0.1 (11601.2.7.2) for safari and Version 52.0.2743.116 (64-bit) for chrome. and on Iphone 5s ios9.3.3

**Comment by meganwaps** [comment]
In doing a user test on Friday, the user was actual able to make it past the initial page where they are asked to supply their email address and authenticate. The next page, however, would not let this user save their details, meaning the sign-up process could not be completed.

**Comment by meganwaps** [comment]
-[ ] @markmacgillivray Could you possibly send us screenshots for the areas of the site that we are unable to access?

**Comment by JosephMcArthur** [comment]
Can you let us know the set up for the user who got past the first page?
Hardware / software versions etc.

**Comment by chealsye** [comment]
Google Chrome Version 53.0.2785.116 (64-bit)
OS X Yosemite Version 10.10.5 (14F27)

I know, Joe, I need to update.

**Comment by markmacgillivray** [comment]
I have changed the UI process for this, to perhaps make it a bit clearer. I have also altered how the login UI code behaves when it sends requests to the API - some browsers do not properly handle the response codes, so now I show the login token section regardless of API response code. This is not ideal but perhaps the only way around shoddy browser implementations.

There may still be further issues to solve with the login process, so I have also configured it to send me an email every time someone encounters a login error, so I can see all the info about their problem.

The login UI now no longer shows an expired message, and no longer shows a "login" button when awaiting the login token. Instead there is the box for an email address which will be shown whenever the user is not successfully logged in, along with the signup / login button. Once the signup/login button is pressed, the email address box and signup/login button should disappear and be replaced by only a box that can accept the login code. There is no longer a login button here at all. So at this point the only thing the user can do is go and check their email. Once they do, they either click the link in the email or put their login code in the box. As soon as a login code of suitable length is entered, it will be validated and the user will be logged in if correct or shown an error request to restart the login process if not.

This should make the login workflow simpler, with less places for things to go wrong or misleading actions to be taken. The texts below the login area still seem suitable for explaining the process.

Please all try logging in again on the dev site, and let me know of any more issues (there may still be some, but this should move us forward, and I will get more useful error data sent to me by the system this time round). Thanks @JosephMcArthur @meganwaps @chealsye

**Comment by markmacgillivray** [comment]
I just got some login error info - thanks to whoever tried that! It still appears to be an issue with accepting the hash from the URL, but this is progress

**Comment by JosephMcArthur** [comment]
That was me. Tried the link and code, neither worked on android.

Not commenting on actual changes right now, just testing. Sounds good
though.

**Comment by meganwaps** [comment]
Just tried to login on the test site using
Chrome Version 53.0.2785.116 (64-bit) and
OS X Yosemite Version 10.10.4   

I was sent an email after entering my email address, but when I clicked on the authentication link: 
![screen shot 2016-09-29 at 11 58 35 am](https://cloud.githubusercontent.com/assets/5968703/18968092/8430231e-863c-11e6-9945-d3da70d3d842.png)

After clicking on the link I was redirected to the Sign Up page again but with no indication that I'd ever entered my email in the first place. 
![screen shot 2016-09-29 at 11 58 44 am](https://cloud.githubusercontent.com/assets/5968703/18968123/a6ea9b00-863c-11e6-8b9e-6db1850c20ab.png)


Hope this helps, Sorry if I conducted this little test while dev changes were being made!

**Comment by markmacgillivray** [comment]
Hi thanks this is good, I'm getting the error data I need from your
attempts. Will investigate further.

**Comment by markmacgillivray** [comment]
OK I have investigated the further information I received from the tests yesterday, and I think login may now be fixed, and also have a simpler UI workflow. Please all try again when you get a chance and record any more issues here.

**Comment by markmacgillivray** [comment]
Ah, but there may be issues with the email addresses you all use having been incorrectly logged in the dev system, which may still make things look like errors for you all, so please wait until I remove those from the system, I will update this issue again once done.

**Comment by markmacgillivray** [comment]
OK the old accounts have been cleared now, try again whenever suits

**Comment by JosephMcArthur** [comment]
[YES. I CAN LOGIN (on my normal Chrome set up, not tested further)](https://youtu.be/DhrfhjLd9e4?t=12s)

However, I couldn't save my details / download after that.

**Comment by markmacgillivray** [comment]
Good! Save details / download is disabled at the moment, no problem there.

**Comment by JosephMcArthur** [comment]
Fab. This is working far more smoothly. The email is delivered faster than I can switch tabs, and the links / code entry seems fast. Just tried on my phone and that worked too. 

I think more UI changes on this & other parts of the process would be done, but if @chealsye @meganwaps @natalianorori can confirm that the email code system is working for them then we're golden to close this.
