### ISSUE TITLE
'Check your email' message on test site-too small

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#239]
Noticing that the alert to check one's email for a validation code is quite small, and the gray coloring inside the text box is difficult to read- on top of that, the message itself disappears if someone clicks inside that text box. Suggest a prompt with more visibility.

**Comment by JosephMcArthur** [comment]
I suggest it appears to the right of the login button on desktop, or below on mobile. How the error messages currently appear.

**Comment by markmacgillivray** [comment]
Added a message below the box, in black.
