### ISSUE TITLE
Add final "Download" Bar on homepage

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#240]
As seen here: https://www.dropbox.com/s/2eepti6eaf9id09/Screenshot%202016-09-19%2015.06.38.png?dl=0

**Comment by markmacgillivray** [comment]
We already have this up near the top on the right now - a box saying to sign up and get a plugin. Is it worth replicating at the bottom again? Seems like overkill.

**Comment by markmacgillivray** [comment]
@JosephMcArthur awaiting answer on this. unassigning myself for now, let me know if really wanted.

**Comment by JosephMcArthur** [comment]
Nope, if we make a change I think it should be adding search.

**Comment by JosephMcArthur** [comment]
p.s I may change my mind here, but shutting this now as i feel its unlikely.
