### ISSUE TITLE
Request page redesign

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#242]
### Request page

This style is a fairly radical departure from what we have now. I have my doubts about it, but this is what he suggests we think about. Obviously, we can take it or leave it, or take bits and leave others. Up for discussion. 

![request editing page ux](https://cloud.githubusercontent.com/assets/4953703/18549725/15308fd4-7b48-11e6-8390-7f520cd1cef6.png)

Forked from #232

**Comment by markmacgillivray** [comment]
Didn't follow this too closely, but have redone the request page, functionality still in progress

**Comment by chealsye** [comment]
@JosephMcArthur Do we need the phone number? I'm very iffy on that. Otherwise I think this is different, but it could work well. I like that it is both for the author and users to help. It's friendlier, invites sharing. Have some tweaks and new copy, but want to give it a try. If after user tests and initial launch it isn't working like we want we can revisit and tweak.

Updated copy @markmacgillivray 
![15308fd4-7b48-11e6-8390-7f520cd1cef6](https://cloud.githubusercontent.com/assets/9299248/19224209/0edfce0a-8e4f-11e6-8b45-c65a1305bdee.png)

**Comment by markmacgillivray** [comment]
Note at the moment the request page does not look like this at all. It was
previously questioned that this style was desirable. I do not think we
should use an overlay style, and also we do not have sufficient information
to make this work - we have no user profile pictures, and actually no
reason to collect author information at all; we only need email addresses.
We have no subject information either - do we want to start collecting
this? As soon as we start collecting things we do not have, it makes it
obvious that we do not have them, whereas if we don't ask for them in the
first place, it looks simpler and better.

It feels to me like over-designing, without functional reasoning. In fact,
whilst tidying the data over the last week, I have been thinking there is a
lot of data we have occasionally tried to collect without any clear purpose
at all - as noted above, all we actually need to get requests working is
URLs to the content and email addresses to contact, and the title, story,
and DOI give all the context necessary. I've worked on a few projects over
the years that get bogged down in this desire for metadata, and yet most of
them have never identified a real need for it - if you have the URL, you
have all the metadata you need.

Probably something to discuss tomorrow.

**Comment by JosephMcArthur** [comment]
Agree with much of Marks assessment here, happy to close this for now. Any further changes to the site can be done from what's on the test server.
