### ISSUE TITLE
Get copy for emails into static repo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#243]
I thought it was already there, but it isn't. This would be EXTREMELY useful!

**Comment by JosephMcArthur** [comment]
@markmacgillivray can emails be done in Markdown / HTML or do we have to use the other notation that some email systems use? The one with /n for new line and things like that.

**Comment by markmacgillivray** [comment]
html yes, plus handlebars for putting in variables. Maybe markdown.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we get this in asap? Lots of pages on the site are supported by email & we should lock in and test those before the new site goes up ideally!

**Comment by markmacgillivray** [comment]
Yes it's next on my list.

**Comment by JosephMcArthur** [comment]
So you're aware, once this in we're planning to start a bunch of issues relating to individual emails that need to be sent on certain q's.

**Comment by JosephMcArthur** [comment]
There is now an example template for emails into oabstatic email folder

**Comment by markmacgillivray** [comment]
Done an example.txt that explains how to use, and also an example one to send to author when status changes to progress. I will later be making it possible to test that one, so the feature can be seen in action, but there is already an issue about making it possible to test emails from the admin area, so closing this one now.
