### ISSUE TITLE
Move map/quote slider dots down

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#247]
The slider dots for the map quotes cut off some of the attribution. We need them moved down just a bit to prevent this cut off.

![screen shot 2016-09-19 at 12 00 47 pm](https://cloud.githubusercontent.com/assets/9299248/18639156/c1a49e84-7e60-11e6-9bb1-4b57e503651b.png)

**Comment by meganwaps** [comment]
In the test I just ran we also discovered that some of the quotes were being cut off, some letters were almost completely cut in half on the far right.
