### ISSUE TITLE
Changing Site Font from Raleway to ?

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#248]
I'd like to move away from the Raleway font. Any support or suggestions? Should everything be in Montserrat? Is a font change something Mark needs to do?

**Comment by chealsye** [comment]
Yes, I can edit PSD files.

**Comment by JosephMcArthur** [comment]
This is a page for Montserrat with suggested pairings - https://fonts.google.com/specimen/Montserrat

**Comment by JosephMcArthur** [comment]
Okay, he suggests Monserrat as header font with Roboto Light as the body font! 

@chealsye can you edit the style guide to match this. Then we can close this.

**Comment by chealsye** [comment]
Roboto will provide a better look. Awesome!

Do you mean the original design guide we got two years ago?

**Comment by JosephMcArthur** [comment]
Nope, I'd work on the one in this thread.

**Comment by chealsye** [comment]
Ah sorry. Forgot that was up there! Will locate the file and update it.

**Comment by chealsye** [comment]
I updated both fonts in the style guide and uploaded it to the repo. I know the designer suggested Roboto Light, but I think it is too thin for our site and would recommend keeping Roboto Regular. I'm also going to send the team an email with the style guide and instructions for installing Roboto, so they are aware and we can keep consistency.

**Comment by chealsye** [comment]
Here are two screenshots of Roboto Light and Roboto Regular. Here you can see the weight difference between the two. I think Roboto Regular will be better for the Button site. I think too thin of font could be potentially difficult to read.

![screen shot 2016-09-25 at 12 02 45](https://cloud.githubusercontent.com/assets/9299248/18816641/ea9cc946-831b-11e6-9065-9eb6d4f5dddc.png)
![screen shot 2016-09-25 at 12 03 17](https://cloud.githubusercontent.com/assets/9299248/18816640/ea997ac0-831b-11e6-92ec-405fdb16224b.png)
