### ISSUE TITLE
What should we do with OpenDataButton.org?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#251]

**Comment by meganwaps** [comment]
My suggestion would be to redirect users to the new site which integrates the two, keep it up for a few months after the launch and then shut it down after the New Year?

**Comment by natalianorori** [comment]
I agree with Megan, perhaps we could also add a little explanation that states that both of the sites are merging as well

**Comment by chealsye** [comment]
Have it redirect to a specific page explaining the merger for x months, not the main OAB site. Include a sign up button on that page.

**Comment by markmacgillivray** [comment]
Assigning to me to do the domain pointing

**Comment by chealsye** [comment]
@markmacgillivray, where are you redirected it to?

**Comment by markmacgillivray** [comment]
As described, a page that explains the merger, offering them a sign up /
sign in. I'll just call the page odb or something. Unless you want to write
a more comprehensive blog post explaining the merge? If so just let me know
the blog page name once you write it. Redirects just take a few minutes.

**Comment by chealsye** [comment]
OK - I asked, because you unassigned me from the issue and I thought you might just be redirecting to an already existing page, such as just the homepage instead of a new page. The text for a new page is going to need to be created. It won't be a blog post.

**Comment by markmacgillivray** [comment]
OK makes sense for you to make a page first, then let me know when you want the URL directed.

**Comment by JosephMcArthur** [comment]
@markmacgillivray do you need David to do the redirect - or can you do it with the access you have?

**Comment by markmacgillivray** [comment]
The domain name points to my server now so from there I can redirect it
without accessing the DNS settings.

**Comment by JosephMcArthur** [comment]
Have we thought about if people hit pages like /account, it might make sense to redirect to their equivalents directly? I think if they land on the homepage what is above makes sense.

**Comment by markmacgillivray** [comment]
We can do that too. All I need to know is which page the main domain should
be redirected to, i.e. the one explaining the move. Then I can redirect
pages to their equivalents if that is how you want it. Just let me know
once the choice is made and I can update the settings when we are ready to
go live.

**Comment by JosephMcArthur** [comment]
@markmacgillivray , if we redirect from opendatabutton.org is it possible & feasible to have an info box at the top of the site with a line or two on the change? 

That feels like it could take care of call of this, and we can just straight redirect all pages (except the occasional page that has no equivalent, in which case we redirect to homepage)

**Comment by markmacgillivray** [comment]
Probably, I'd have to test and add a little js to the page to catch some
sort of signifier, then display a hidden div. If someone can write the
content for that div and put it in with style="display:none;" and some id
like id="fromopendatabutton" then I can test a way to trigger it.

**Comment by JosephMcArthur** [comment]
Suggest content while @chealsye wakes up:

> The Open Data Button has now merged with the Open Access Button. Your account and request will stay the same, but you'll need to get the new plugin. For more on the changes see our <a href "/blog/new-oab-2016">blog</a>.

**Comment by markmacgillivray** [comment]
Actually the blog is still an open question too...

**Comment by JosephMcArthur** [comment]
Keeping it as is for now, the new blog is up on dev.

**Comment by JosephMcArthur** [comment]
This new bit of text is in the header file, and should be building now. Copy is changeable, just needed something representative.

**Comment by markmacgillivray** [comment]
Having just tried to look at the blog on mobile, I find I cannot scroll
down pages any more. Any idea what caused that? The account page still
scrolls fine, so it can't be a general issue with the site code.

**Comment by JosephMcArthur** [comment]
happening on desktop for me too - it'll be the code I just put in.

**Comment by JosephMcArthur** [comment]
Okay, the bar you requested is in, scroll is back & everything seems to be acting as you'd expect.

**Comment by markmacgillivray** [comment]
OK I'm at the uni for a few hours, then will get as many issues closed as
possible

**Comment by markmacgillivray** [comment]
The alert message that @JosephMcArthur added can now be triggered by adding ?odb=true to the URL. This will be done automatically if anyone goes to an opendatabutton.org address - they will be redirected to the equivalent page on openaccessbutton.org, but with that parameter added, and they will see the explanatory message.

**Comment by JosephMcArthur** [comment]
Just reopening as we need to : 
- [ ] allow the message to be closeable & add that to the request page message too. 
- [ ] move it out the top bar (possibly) so it's under.

**Comment by JosephMcArthur** [comment]
The above changes are now in. 

@chealsye can you close when you're happy with the copy here.
