### ISSUE TITLE
New team page code needed

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#256]
The new team page needs to be added to the OAB test site. Unfortunately, I'm not able to create it. I can handle putting the names in, but the photos make it more complicated and I could really mess it up. @markmacgillivray, could you take this?

The team page draft is in a Google doc: https://docs.google.com/document/d/1T-r7OJ9Q-a82wciLUlVHvY9AEhXRQOBn2LL2arIX1Nk/edit
Team photos are here: https://drive.google.com/drive/folders/0B3zC2zJzpxoIYzBERTR1M1RVd1k

In the Google doc there is an example of the look I'm aiming for with circular photos of the team members.

I'll add in Alex's photo tonight. I'm waiting for a photo from Jess, but if it's not in there when you create the page I can go ahead and add it in later since the code will be established then.

One last bit that needs to be decided is if we include alumni as a separate tab or if it just displays below. Personally, I think a separate tab would be cleaner - but can the about page have a sub-section to the "Team" tab? Or will it need to be just another tab for Alumni? If so, then I think we just need to include it below the photos and names of current team members.

**Comment by JosephMcArthur** [comment]
@chealsye can you get as much of the new copy up as you can without needing the styling? That'll make it easier for Mark to come in later and just add photos + stops this blocking up moving forwards

**Comment by chealsye** [comment]
@JosephMcArthur It would be easier for @markmacgillivray to add the photos in first. The names have to be formatted under, so it would make more sense for the photos to be there. But yep happy to do the rest!

**Comment by JosephMcArthur** [comment]
So, photos can be added by anyone the same way files are added. Would certainly be helpful if you could do that part. 

Then, we could just part of an open source template for the page e.g https://startbootstrap.com/template-overviews/round-about/ (actual code here: https://github.com/BlackrockDigital/startbootstrap-round-about/blob/master/index.html starting at around line 76) . That has 90% of what we'd need I expect.

**Comment by chealsye** [comment]
Fine. I'll learn how to do it.

**Comment by JosephMcArthur** [comment]
Ace, if you have trouble ping me. This is also something I can probably try
and do if you have too much other stuff on.

**Comment by chealsye** [comment]
OK -- all the problems have been fixed now and the team page is up. Thank you both.
