### ISSUE TITLE
Emails to be sent upon a request being made

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#264]

**Comment by markmacgillivray** [comment]
When creating a new request, trigger the email that asks the user to go and review their new request.

**Comment by JosephMcArthur** [comment]
@markmacgillivray I expect it would be helpful if you could do a version of this that gives the info needed for functions. Then Chealsye can clean up & hone.

**Comment by chealsye** [comment]
I started a draft a week ago, but it was lower on my list of needed copy so it's not done. It would be helpful @markmacgillivray if you could provide a brief paragraph of that gives info needed for functions. Or if you have screenshots/links of the process that works too!

Originally I interpreted this issue as needing copy for the email that would be sent to the author. Do you need this and the one Mark noted for the user to review their request, @markmacgillivray?

**Comment by markmacgillivray** [comment]
Moving to later milestone for easier overview

**Comment by markmacgillivray** [comment]
There is now an example.txt email, and also an author_request.txt email, which is an example of how an author request email could be written, and it would get sent to the author email address when the status of a request changes from moderate to progress.

**Comment by markmacgillivray** [comment]
https://github.com/OAButton/oab_static/blob/develop/emails/author_request.txt

**Comment by JosephMcArthur** [comment]
This was a user email, but I think since we're sending them directly to the page this is fine.
