### ISSUE TITLE
Plug-in opening on things which aren't articles

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#267]
@JosephMcArthur commented on [Sat Jun 18 2016](https://github.com/OAButton/unified-extension/issues/6)

---

@JosephMcArthur commented on [Sat Jun 18 2016](https://github.com/OAButton/unified-extension/issues/6#issuecomment-226932332)

- [x] How do we handle this? 

---

@JosephMcArthur commented on [Mon Sep 12 2016](https://github.com/OAButton/unified-extension/issues/6#issuecomment-246239045)

Designer has suggested this, awaiting confirmation from @markmacgillivray on implementation.

**Comment by markmacgillivray** [comment]
@JosephMcArthur what should I be doing with this one?

**Comment by JosephMcArthur** [comment]
When the plugin / website request page (we need a better name for this) opens on something that is:

* on our black/filterlist --> show a nice message suggesting they should check out the instructions
* if our system can find no title or DOI --> allow for manual input or to report gracefully (e.g #274) 

This is all shown in #226, specifically here: https://github.com/OAButton/backend/issues/226#issuecomment-251654546

**Comment by markmacgillivray** [comment]
ok thanks for the reminder

**Comment by markmacgillivray** [comment]
Done, blacklisted sites now trigger a message saying no and linking to instructions page. Handling missing info will be done on the request page.
