### ISSUE TITLE
Start a request (from the website) page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#268]
Adding as this is something we've discussed wanted to deliver, but don't have down in issues. 

As we know, this page can functionally be similar to the plugin and request pages. However, there might be some significant UI differences. My concern for this page is how we handle things if the paper / dataset is already availiable.

**Comment by chealsye** [comment]
Would the the request from the website require a users email address? Is the Button capable of having a request submitted through a form, searched, and then emailed that day if it is indeed available? I'm not sure how the tech works for the request on the website.

**Comment by JosephMcArthur** [comment]
Simply, yes, it is now.

**Comment by markmacgillivray** [comment]
I don't think there is particular copy needed for this, is there? There is a functional new request page now, and I will add to it a check to see if already available or already requested, and where either is true, a statement saying so with a redirect link is all that is needed.

**Comment by JosephMcArthur** [comment]
I imagine some copy on what a request is on this page might be helpful, as well as supporting copy with the text entry fields to ensure we're getting good data.

**Comment by markmacgillivray** [comment]
OK, that can be added to the new request page at any time.

**Comment by chealsye** [comment]
The request via the website pages currently look like this:
![screen shot 2016-10-10 at 9 58 17 am](https://cloud.githubusercontent.com/assets/9299248/19239885/05440546-8ed6-11e6-84b2-b2bb4df75dcb.png)
![screen shot 2016-10-10 at 9 57 49 am](https://cloud.githubusercontent.com/assets/9299248/19239888/08e7cf16-8ed6-11e6-9e12-d1fd4e542d7c.png)

These are my suggestions - bring down the boxes from the top bar, use a more neutral color, new copy:

![examples 5](https://cloud.githubusercontent.com/assets/9299248/19239901/1317c3d8-8ed6-11e6-8e41-17ae3fb16631.png)

If it is possible to allow users to sign up without needing to click through to another page. If not then just remove email and send them to the sign up page.

![examples 6](https://cloud.githubusercontent.com/assets/9299248/19239924/2dfe091e-8ed6-11e6-9856-2b99408c1c82.png)

![examples 7](https://cloud.githubusercontent.com/assets/9299248/19240035/a3604ee2-8ed6-11e6-8abe-91c4a2838fcb.png)
