### ISSUE TITLE
Clicking filters multiple times on the request page leads to filter tab being added several times

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#270]
### Expected Behavior

Clicking "Articles" many times only leads to the filter being applied once

### Actual Behavior

Clicking "Articles" many times only leads to the filter being applied many times

### Steps to Reproduce this bug

* Hardware versions: Mac
* Software versions: Chrome
* Steps to reproduce:
 * Go to /request
 * Click any filter
 * Click that filter again

**Comment by markmacgillivray** [comment]
Fixed. Where there is only one filter value of a given type, it should not display at all (because with only one type it can have no useful effect in the result list). Because this was not happening, it was possible to still see and click the filter link over and over again.
