### ISSUE TITLE
Fix slider quotes from being cut off

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#271]
The quote slider on the homepage cuts off some quotes. Either the quote needs to come in or the width of the slider be expanded. 

![screen shot 2016-10-07 at 20 15 59](https://cloud.githubusercontent.com/assets/9299248/19208665/28043b58-8ccb-11e6-935e-16897c3bb130.png)

**Comment by JosephMcArthur** [comment]
Just added a break line to the offending quote.
