### ISSUE TITLE
Update User Registration Page

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#272]
Here's some suggested tweaks to the user registration page. @markmacgillivray, could you do this? Let me know if anything isn't clear.

![screen shot 2016-10-07 at 21 58 04](https://cloud.githubusercontent.com/assets/9299248/19209506/7d63266e-8cd9-11e6-94a4-51698466dc08.png)

-Change background colour to light grey
-Change logout and save your details button colour to light blue 
-Remove Hello
-Change "I understand that information obtained by this button will be publicly accessible" to "I understand that information obtained by the Open Access Button will be publicly accessible.
-Remove "By the way we have a brand new plugin coming really soon, in October 2016, combining up the open access and open data plugins all into one, and with some great new features! Check back soon for more info."

![registration](https://cloud.githubusercontent.com/assets/9299248/19209629/725551c2-8cdc-11e6-984f-8514cadf824f.png)

**Comment by JosephMcArthur** [comment]
On top of this, my suggestions are:
- [ ] move logout below save your details (if have it at all)
- [ ] since the user hasn't downloaded the plugin at this point to remove the API key. 
- [ ] remove orcid, it's not useful at this point for users to have them. 
- [ ] have "name" instead be "full name"
- [ ] have "select your proffesion" be "select the profession which best describes you"

With those suggestions, I'm not 100% sure how the 1/2 width thing would look -  but generally I can see it being an improvement.

**Comment by chealsye** [comment]
I'm OK with either width -- but I wanted the API/logout separate from the registration form. If both are removed, that's fine. I do think the current registration page with the full width bars is too wide.


![examples 4](https://cloud.githubusercontent.com/assets/9299248/19216955/8a852d30-8d9f-11e6-840e-bf6ad05eadd8.png)

**Comment by JosephMcArthur** [comment]
Except on small screens, where full width makes sense :)

**Comment by markmacgillivray** [comment]
Why make something half width if we have nothing else to use the space for?
API key can be removed. So can logout button, but then nobody can log out.

**Comment by chealsye** [comment]
White space can be good. As a user I think the current registration screen is overwhelming and too large. Right now I can't think of a user registration on another site that takes up a full screen on a laptop. I modeled my copy after Slack at Joe's suggestion, which set up steps are centered and not full width.

Logout should definitely stay then, below save your details. Would like it in orange.

**Comment by JosephMcArthur** [comment]
I agree, whitespace is good.

I assume we can have the logout button on latter pages, like the account
page?

Joe

**Comment by markmacgillivray** [comment]
Can change this and close once current DNS issues are solved.

**Comment by JosephMcArthur** [comment]
I think most copy changes here are important - but design changes can wait.

**Comment by markmacgillivray** [comment]
Copy done, design changes can come in a later round, for now the design matches better across pages and changing them all would take more time than is currently available. Will unassign myself as I am trying to track what still needs done by me.

**Comment by JosephMcArthur** [comment]
Trying to test this. Mark, can you clear my account details for joe@righttoresearch.org / jose@sparcopen.org / joseph.mcarthur.10@gmail.com OR let me know why having a plus in the address stops the email sending. I use "+" to fool these sign up forms into thinking I have a new account but still getting emails. 

Once I can double check copy, we're good to close.

**Comment by markmacgillivray** [comment]
Plus sign was causing an unexpected issue, fixed now. You should be able to make accounts with joe+whatever@blah.com and they will come through to you.

**Comment by JosephMcArthur** [comment]
Great! That works now. 

@markmacgillivray have made a pull request to close this - just want to make sure I'm not making for issues than I fix.

**Comment by chealsye** [comment]
Yeah, it's fine to close.

**Comment by chealsye** [comment]
None of my copy. This is how it looks when I view it -- the only change I see is removing the API key and additions that weren't my copy to the fields.

![screen shot 2016-10-14 at 11 25 41](https://cloud.githubusercontent.com/assets/9299248/19394984/f89b1644-9200-11e6-941f-ab0684a62263.png)

**Comment by chealsye** [comment]
But fine close.

**Comment by JosephMcArthur** [comment]
All the above changes should be in now. However, @chealsye there is an error message you may not have seen. 

> Sorry, some information is missing. Please ensure you have filled in all the fields above and that you have checked the confirmation boxes too, then try saving again. Thanks!

Any suggested changes to that? I imagine we can make that shorter.

**Comment by markmacgillivray** [comment]
As an aside, when I am developing functionality, I have to put something in
these places, such as that error text. If I put nothing in there, it is
very hard to track what is being triggered on the page. Also, if I make it
something relevant, it is easier to edit it later, and actually it can be
directly edited by anyone with access to the repo, so a larger explanation
rather than just "ERROR HERE" helps it stand out for everyone. It does not
mean that I think the text should be as I write it, and it does not mean I
intend to ignore suggestions from anyone else. When things should say
something else and I have missed them, just let me know. I am happy to
change such texts as directed, apart from when it does not coincide with
the functionality, in which case I will bring up the issue - not to
override decisions on content for the sake of it, but to ensure we have
content that matches functionality.

**Comment by chealsye** [comment]
@JosephMcArthur 

"Some information is missing. Please confirm you have completed all the fields and checked the boxes. Then save again." is a bit shorter and tighter.

**Comment by JosephMcArthur** [comment]
this is in & tested (the message comes up). Closing now, any further changes (unless something has been missed above) can be made as new issues. Design changes are included in #281 and can be made as capacity becomes available.

**Comment by JosephMcArthur** [comment]
Sorry, I've missed something here. While testing #265 (which worked so nicely) I noticed some text about sign up we've not honed yet. 

#### text that displayed for me after playing around with multiple accounts & downloading / installing the dev plugin on chrome

> Your API key appears to have been changed.
Do you want to save the new API key caae0f5ed26f5166caffcbffa78cdd into your plugin?

Button text: Yes, save the new API key to my plugin!

#### displayed after I accepted the above

> Your API key caae0f5ed26f5166caffcbffa78cdd is stored in your plugin.

@markmacgillivray I can't see this text in the account page, is there other text that can come up here we should know about? 

@chealsye in terms of copy here, it would be good to not use the words API Key. I only just about understand what this is, I can't imagine most users will.

**Comment by markmacgillivray** [comment]
It could just say "your plugin has been authorised" if you want. I think
that text is injected by the plugin, so no you can't find it in the
oab_static repo.

**Comment by chealsye** [comment]
Is there a reason the plugin needs to say anything at all to the user? Was this a problem because you were signed into the plugin you downloaded but then on the website you were under a different email?

**Comment by markmacgillivray** [comment]
If someone installs the plugin from chrome they are directed to go to the
site to get authorised the first time. So it has to say something to
confirm to them that this has happened. Also if someone wipes their
browser, or something like that, they'd be directed to the site to get
authorised. But it could be something as simple as "OK you're authorised".

**Comment by JosephMcArthur** [comment]
Words like authorized still probably don't mean much to people. I'd suggest we try and just be clear about what it means to a user. In that case "OK you're authorised" becomes "OK you're ready to use the chrome plugin". Not saying the latter should be copy, just an example of how we can change technical words into meaningful info for a user.

**Comment by chealsye** [comment]
Hmm… yes, authorised still feels technical and doesn't feel meaningful.

What about simply something like
>  Your account is set up!
>  Your plugin is set up!
> Your new Button plugin is ready to use!
> Your new plugin is now ready to use!


For an error when the installed plugin and account don't match (which I imagine won't be frequent) I think similar what Joe has already suggested can work well. 
> The account associated with your installed plugin isn't the same as this account, do you want to change it?

**Comment by JosephMcArthur** [comment]
Given we're now discussing copy which lives in the plugin, moving to the mini-milestone for plugin releases.

**Comment by markmacgillivray** [comment]
Update it with what?

**Comment by JosephMcArthur** [comment]
>Your API key appears to have been changed.
Do you want to save the new API key caae0f5ed26f5166caffcbffa78cdd into your plugin?

to

> The account associated with your installed plugin isn't the same as this account, do you want to change it?

> Your API key caae0f5ed26f5166caffcbffa78cdd is stored in your plugin.

to 

> Your plugin is now ready to use!

As long as I'm understanding the above correctly. 

Is there any other copy we haven't discussed above coming from the plugin?

**Comment by chealsye** [comment]
Your plugin is now ready to use! isn't accurate, is it? This is the account registration page. The plugin isn't yet installed, right? 

So, shouldn't it be
> Your account is now ready to use!

**Comment by JosephMcArthur** [comment]
That message will _only_ display when it is ready. So you'll click to download it, then when you return to the page it'll display that message.

**Comment by chealsye** [comment]
Okay, thanks for clarifying.

**Comment by JosephMcArthur** [comment]
This is another message that can display:
> Your API key could not be found!

Instead, perhaps

> We couldn't connect your account and plugin, somethings up. Email us to zyx

**Comment by JosephMcArthur** [comment]
Okay, the confirmation message is always shown. So, suggesting we remove the "now".

> Your plugin is ready to use!

**Comment by markmacgillivray** [comment]
There did not appear to be copy for all the sections of the part of the plugin that interacts with the page, but I have tried to use what appears to be the final statements from all of the above, plus a couple more to match in and complete the set. Here is everything it says:

Your plugin is installed! Just associating it to your account for you...

We couldn't connect your account and plugin, something is up. (NOTE this one is supposed to have an email address I guess, but none is stated above)

The account associated with your installed plugin isn't the same as this account, do you want to change it?

Yes, connect this account to my plugin!

Your plugin is ready to use!

All in this file: 
https://github.com/OAButton/unified-extension/blob/develop/js/account.js

I will unassign myself now, I think this is everything, after checking feel free to close. Or assign back to me if particular updates are necessary, and if nobody else can do them.

**Comment by JosephMcArthur** [comment]
@markmacgillivray i added 

> email help@openaccessbutton.org

Will the "@" be okay in the text? I saw you had to put "/" in front of some characters. 

If it's okay, I'm closing. @chealsye if you have second thoughts on any copy please reopen.

**Comment by markmacgillivray** [comment]
The @ should be fine.
