### ISSUE TITLE
Implement a Bug form

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#274]
It would be good to make a bug form that streamlined us getting info about bugs. I imagine a form that captured:

* Browser / Hardware info (optional: automatically)
* Description of the issue
* email of the descriptor
* what system (website / plugin etc) the bug is found on
* how we can reproduce the bug
* what they expected the system to do
* any images

would be useful. Some of this could be done with a gform (@chealsye) and later made nicer smoother with something native. I've also seen typeform be used to great effect for bug forms, it's a little more powerful. 

These forms should email bugs@openaccessbutton.org, which should then direct into this repo (using the intergration @markmacgillivray has made for emailing issues).

**Comment by JosephMcArthur** [comment]
have made copy on this page less bad for right now.

**Comment by JosephMcArthur** [comment]
We have a bug form on the page now. 

Questions should be fine. @markmacgillivray tell me if others are useful. 
https://docs.google.com/forms/d/15KWEat3SeRjU0o9nnnI6PyHQP6EF0gjodRBzf0KsdB0/edit

@chealsye copy is your call, I've just given a starter here that I hope isn't too awful.

**Comment by chealsye** [comment]
It's fine.
