### ISSUE TITLE
oab_static index.html doesn't align with what's on the master / dev sites

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#275]
Both the master & dev branches no longer seem to align with what's on the website e.g https://github.com/OAButton/oab_static/blob/master/content/index.html is not what's on the site currently.

**Comment by markmacgillivray** [comment]
Can this be closed now? We have the dev site aligned, and we know what the issue was with master.

**Comment by JosephMcArthur** [comment]
Given discussions via email yesterday - yes
