### ISSUE TITLE
increase form font size to 20px

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#282]
I believe this code comes from the CL repo.

**Comment by markmacgillivray** [comment]
I don't know what you mean. Which form? All forms? There is no code from the CL repo driving the UI now, it is all in the oab_static repo. The CL repo only drives the API.

**Comment by JosephMcArthur** [comment]
Yeah, all forms, like email submission & sign up. 

I think the code for it lives in a static.cottagelabs file. 

<img width="1277" alt="screenshot 2016-10-14 13 50 10" src="https://cloud.githubusercontent.com/assets/4953703/19387974/3ef6a02c-9215-11e6-8667-c14c6934dfe1.png">

**Comment by markmacgillivray** [comment]
In that case it will just be the default bootstrap size. This can be
overridden on the /static.oabutton.css file. 20px sounds kind of large
though. Also usually it is better to dynamically size text using em rather
than px. I can try some different scales if you want.

**Comment by JosephMcArthur** [comment]
using em sounds better. Essentially I think text in form boxes should be as large as text on the page - maybe a hint smaller. If we think the text on our page is big enough to be readable easily, our form text should be just as big. Especially since we tend to up instructions in it.

**Comment by markmacgillivray** [comment]
Form font size has been set bigger, to more closely match page text size. @JosephMcArthur assigning to you to have a look and close.

**Comment by JosephMcArthur** [comment]
Looked quickly:
* has this been done on mobile? 
* it looks messy on the sign up info section

generally assigned megan to take a deeper look.

**Comment by markmacgillivray** [comment]
Yes should apply to mobile too - certainly looks bigger on my test view.

There are potentially some places where the larger text will look bad, yes - there has to be a balance between the fact that the input boxes themselves take up more space, so either need smaller text inside them or to be quite a bit bigger themselves, which makes them chunk out of the text a bit too much.

The text is a fair bit bigger than it was, now much the same as other page text. We can scale back down slightly whilst still being bigger than it was before, so once @meganwaps has a look, let me know if it could be a little smaller.

**Comment by JosephMcArthur** [comment]
Lets scale it down a bit now.

**Comment by markmacgillivray** [comment]
OK, scaled down a bit

**Comment by JosephMcArthur** [comment]
This feels better.

**Comment by JosephMcArthur** [comment]
Okay, on login this leads to:
* the username field being too large. To fix:
- [ ] Say "Username (required)"
* the profession field not showing fully before click. Not sure how to fix. 

It looks fine on /request/new

**Comment by markmacgillivray** [comment]
Shortened username and shortened profession text to "Profession (requried)" which matches better with the other placeholder texts anyway. Closing, but reopen if necessary.
