### ISSUE TITLE
Adjust copy so that /request/new isn't new request page, just oab in a webpage

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#285]
I realise we've been calling /request/new a "make a request page", and the current (minimal) copy suggests this too. But, does it not do basically everything the plugin does anyway? Give it a URL, it'll try & find stuff, if that doesn't work make a request.

**Comment by JosephMcArthur** [comment]
we should probably also link this page from the download section

**Comment by markmacgillivray** [comment]
I don't understand - what is it you want me to do with it?

**Comment by JosephMcArthur** [comment]
Tagged you for this: https://github.com/OAButton/backend/issues/285#issuecomment-254015588 but realised I could probably take a stab at it myself. So now you have a [pull request](https://github.com/OAButton/oab_static/pull/27) instead. 

But I'm also interested on your take on this, do you agree?

**Comment by markmacgillivray** [comment]
Ah right I see what you mean. Yeah can accept that pull request.

**Comment by chealsye** [comment]
@JosephMcArthur - what do you need from me? Didn't quite follow an action.

**Comment by JosephMcArthur** [comment]
The title of the page currently doesn't represent what it does. It talks only about making a request, not that you can also find stuff.

**Comment by JosephMcArthur** [comment]
Also, I think we can have a better c2a on the page. 

- [ ] change save to something more like "Make Request"

**Comment by JosephMcArthur** [comment]
I think we may also want to be clearer that the user should past the article URL into the page to start the process. 

We could do this through:
* greying / hiding other fields until this is done
* through copy in the bar

**Comment by JosephMcArthur** [comment]
& just following up from a quick discussion on chat with Mark. We'll display sharing messages if the page is successful. 

We'll also have this page grab location.

**Comment by chealsye** [comment]
The best way to communicate this is problem to reframe it (maybe not call it a request? Find and Request?) and make it into two steps. Have them enter the url in on one page and if the Button cannot find it, then the other fields appear or if that isn't possible the next page loads and asks for the rest of the info.

**Comment by chealsye** [comment]
@markmacgillivray I've been testing out the browser request to get screenshots and I just want to say it's delightful to see it working so well - fantastic work! I think the ability to use it in the browser is going to be a big help with getting and retaining users.

**Comment by chealsye** [comment]
Does Find and Request Research make it more clear on the main requests page?

![screen shot 2016-10-16 at 22 12 21](https://cloud.githubusercontent.com/assets/9299248/19423379/ca24440e-93ed-11e6-8871-12c9f7d5e5c2.png)

@JosephMcArthur is this text helpful enough?
> You can now use the Open Access Button in your browser! Paste the URL of the research you need in the URL field. Then the Button will search for an accessible copy.

![sdsd](https://cloud.githubusercontent.com/assets/9299248/19424955/cb843a44-93fb-11e6-9f14-62d3fa015b73.png)

I toyed around with calling it something different, but I think referring to it as something like the Button browser is a bigger reframing.

**Comment by JosephMcArthur** [comment]
Have now changed the title to "what do you need" & we're expecting the page to display on the URL box at first.

**Comment by markmacgillivray** [comment]
The title change is fine, but don't bother changing other content in the
new request page just now - once Megan is finished testing I'm going to
change it, and the different functional process may require new content
anyway.

**Comment by chealsye** [comment]
I do like having the search on the front page. That's great! But I do think this is confusing for the user. What's the different between signing up and searching? From the top text it sounds like they need to sign up in order to unlock articles… but then they can just search instead? From the user perspective I'm thinking: um. what do I do?

Should the sign up be removed?

--
I just tested the search from the homepage and wanted to highlight something. I entered the URL, clicked search.

![screen shot 2016-10-17 at 19 24 07](https://cloud.githubusercontent.com/assets/9299248/19459244/866c4fe2-949f-11e6-8cbd-abec9900e2ad.png)

![screen shot 2016-10-17 at 19 24 44](https://cloud.githubusercontent.com/assets/9299248/19459250/8cdecb0c-949f-11e6-9b46-ef2a79f44a4b.png)

It reloaded the page and I was sent to /request/new with a blank search box. I had to re-paste the URL. This will be an annoying experience for a user. 

But! the search was triggered when I hit enter, which is both stated in the bar but also a fairly intuitive action.

![screen shot 2016-10-17 at 19 24 55](https://cloud.githubusercontent.com/assets/9299248/19459256/8fe8d96e-949f-11e6-810c-4fcfebd94d3f.png)

Communicated thinking well.

![screen shot 2016-10-17 at 19 25 05](https://cloud.githubusercontent.com/assets/9299248/19459259/929f5ade-949f-11e6-9f37-756f58f20a29.png)

And then found the article. Yay. But then this text. From a user perspective — user thoughts: I'm confused. What does create a request mean? Why is it showing this when the article is available?

But it would also be very frustrating to display the request form, have a user submit it, and then tell them they can't and need to create an account first.

**Comment by markmacgillivray** [comment]
The URL should be copied in for you, that must be an error. Can fix in the
morning.

I think it's a bit confusing too, and actually I don't think that whole
section looks too good. There are already sign up links in the top right on
the nav, and I think it'd be better just not repeating that with an email
box further down. I'd also suggest just making the search bar bigger,
across that whole section, and moving the text under it.

**Comment by markmacgillivray** [comment]
The "you want to create a request?" Is what we had before. Now that the
page structure has changed, yes, the copy should change. But I didn't want
to just change the copy to something more suitable.

On 18 Oct 2016 00:49, "Mark MacGillivray" <mark@cottagelabs.com> wrote:

The URL should be copied in for you, that must be an error. Can fix in the
morning.

I think it's a bit confusing too, and actually I don't think that whole
section looks too good. There are already sign up links in the top right on
the nav, and I think it'd be better just not repeating that with an email
box further down. I'd also suggest just making the search bar bigger,
across that whole section, and moving the text under it.

**Comment by JosephMcArthur** [comment]
Not sure how I feel about the search bar being the first call to action both because we've not really user tested, or technically tested it super well. There are probably copy ramifications throughout too. 

For tomorrow, I'd be tempted to keep sign up as is, and develop a search bar-centric landing page for logged in users over the next week.

**Comment by markmacgillivray** [comment]
OK, change front page back to how it was for now. For the new request page,
take tomorrow to check it is good enough. I have other things to do
tomorrow anyway so can switch to the new site on Wednesday.

**Comment by chealsye** [comment]
@JosephMcArthur - So we do new site and announcement on Wednesday then?

**Comment by JosephMcArthur** [comment]
@chealsye happy with these changes? https://github.com/OAButton/oab_static/commit/7bf6de62429f5f1da22d644568dd1ae4eab1f53a

**Comment by chealsye** [comment]
@JosephMcArthur Yup!

**Comment by chealsye** [comment]
Just an FYI - the Find and Request Research text on /request is too big for the button :/

![screen shot 2016-10-18 at 01 11 29](https://cloud.githubusercontent.com/assets/9299248/19465290/f3c11e70-94d0-11e6-8b6c-bf013d2d6ea1.png)
![screen shot 2016-10-18 at 01 11 36](https://cloud.githubusercontent.com/assets/9299248/19465291/f4a9e3ee-94d0-11e6-9e16-5997e1a1e30f.png)

Should we do Find & Request Research or Find + Request Research instead? Or should this button be a bit larger (more height) with a different statement for the browser Button?

**Comment by JosephMcArthur** [comment]
Took both suggestions. and is now &, and the button is taller. However, the build is failing at the moment: https://github.com/OAButton/oab_static/commits/develop

**Comment by markmacgillivray** [comment]
Have fixed the merge conflict, and removed the box from the front page. Removing myself from assignment, as at the moment it is just copy changes due here I think

**Comment by JosephMcArthur** [comment]
@chealsye can you suggest / directly change copy for this? 

https://www.dropbox.com/s/tfdosz2egiy7bu1/Screenshot%202016-10-18%2023.52.01.png?dl=0

**Comment by chealsye** [comment]
I wrote that copy. But it was for when someone supports a request instead
of creating one (I believe creating was added). This text in your
screenshot will *only* appear when someone begins a search and then are
asked to signup/login, right? We'll need to explain why they need to. I'm
trying to draft something, but will have to finish it in the morning. This
is OK enough. But would like change it.

**Comment by JosephMcArthur** [comment]
Yes Chealyse, that is probably the case.

**Comment by chealsye** [comment]
I want to keep this simple - but this message pops up when the research is findable and they aren't seeing the request stuff yet, so I think they need extra info on why they need an account. What about this? Too long?

> The research you need isn’t available, but you can create a request!
> 
> You need to create an account first. Sign up now to begin making requests for articles and data. We’ll contact the author to request the research is made available - and then send you a link.
> 
> Already have an account? Login now!

**Comment by JosephMcArthur** [comment]
This is in.
