### ISSUE TITLE
Allow junk pages to be added to the filter list on the fly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#288]
It's been suggested (#187) that this could be done via a Google sheet that automatically feeds the filter list.

**Comment by markmacgillivray** [comment]
@JosephMcArthur could you create a google spreadsheet somewhere in whatever folder you most prefer to keep oabutton stuff on google apps? You don't need to put anything in it yet, just create the sheet and give me access to it and I can configure from there. It is just easier if you create it first where you want it.

**Comment by JosephMcArthur** [comment]
enjoy:
https://docs.google.com/spreadsheets/d/1j1eAnBN-5UoAPLFIFlQCXEnOmXG85RhwT1rKUkrPleI/edit#gid=0

**Comment by markmacgillivray** [comment]
Done. I have added the starting set of URLs to that sheet, and published it. You can add any more that you want into the column.

As we already know the blacklist works via the plugin, all we need to do to see this is working is add things to the list and see if they appear on the blacklist which they do - check the api endpoint with stale set to 0 to see them popping up:

https://dev.api.cottagelabs.com/service/oab/blacklist?stale=0

under normal operation, the blacklist will only check for updates every hour.

I will close this one now, but @JosephMcArthur have a look at the spreadsheet and try putting a value in, if there is anything you are unhappy with then reopen.
