### ISSUE TITLE
How can we test location gathering via the plugins / bookmarklet? 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#289]

**Comment by markmacgillivray** [comment]
Just use it, it will try to get location. I can add something to the
request page UI so that as admin you can see if location was received or
not. Is that good enough?

**Comment by JosephMcArthur** [comment]
That would be fantastic. Doesn't need to sexy, just something where we can
test if it worked.

**Comment by JosephMcArthur** [comment]
Oh, and can you make megan / chealsye / me / natalia admins on the test
system?

**Comment by JosephMcArthur** [comment]
I'm an admin now, and can make others admins. Can see how to test location too (via request pages, if we have it it'll show in the admin section).
