### ISSUE TITLE
Enable request search to search story text

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#290]

**Comment by markmacgillivray** [comment]
Done

**Comment by JosephMcArthur** [comment]
Any advice on how to test this?

**Comment by markmacgillivray** [comment]
The top request in the search list has a story, and that story has the word
story in it. Type story into the search box and it will filter to show
requests with the word story in their story, and that top one will still
show

**Comment by JosephMcArthur** [comment]
Only single words seem to work, yes?

searching "story" brings back too, searching "this is a story" doesn't.

Also, this may be because I used it while you were changing things, but
I've managed to make a duplicate request.

**Comment by markmacgillivray** [comment]
This looks to be working as expected now. On the dev site, there is this request:

http://oab.test.cottagelabs.com/request/ByAEhWpDmnaLteb2H

and in the story for it, it has the phrase "potentially useful paper". There are also other requests with the words useful and paper occurring in them, searching for just the word useful or the word paper return 2 and 6 results, searching for potentially useful paper returns 7, and searching for potentially AND useful AND paper returns just the one listed above.

I will close for now but re-open if I misunderstand.
