### ISSUE TITLE
Auto Email: Signup

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#292]
[All email drafts here.](https://docs.google.com/document/d/1zdBpebZ64WsJ9T1-4xxuN8o4Ob0qRiWwFVW1Ig2eAdE/edit#)

This is the copy for the email that should send when users sign up for the Button.

It needs to be coded for the user's respective confirmation link and login code to appear in the email. Those items are bolded.

--

SUBJECT: Start Using Your Open Access Button

Hi, there!

Thanks for using the Open Access Button. You're one step closer to accessing the articles and data you need. 

Please confirm your email: **[link]**

Or enter this code on the login page: **xxxxxx**

The code is valid for 30 minutes, so be sure to use it soon!

You can track your ongoing requests under [your account](https://openaccessbutton.org/account). If you experience any problems using the Button, let us know!

We look forward to getting you access to research,
The Open Access Button team

**Comment by markmacgillivray** [comment]
Note that a login email should not contain any other information than that
relevant to getting logged in. For example this email contains a link
recommending the user track their ongoing requests at their account - but
if the user were to follow that link at that time, then they would get
redirected to a login request page, which would start the login process all
over again. Keep these ones simple.

Also, saying "please confirm your email" is getting too specific about what
the user will actually be doing - it is not necessarily the case in all
situations that the user will be validating their email - they may also be
subsequently asked for other questions. Again, best to keep these sorts of
email very simple, and only about the act of logging in.

The subject also could be misleading - what if the user is just signing up
with the intent of exploring more of the functionality, perhaps just on the
browser? They may not be intending to use "their" open access button.

**Comment by JosephMcArthur** [comment]
links should be buttons, example styling is here: https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design.

**Comment by JosephMcArthur** [comment]
Hi folks, not a bunch of info above so I"m going to try and do some guessing. @chealsye you're trying suggest copy for the email that gets sent when people first sign up, right?

What I'd suggest is that we don't have that email be the one people get when they sign into their account. The first step of that process is a general step folks may do often to sign in. In which case, something simpler & more generic may be helpful. I've redrafted below but I've tried to maintain a friendly line & replace the link with a button. (Mark, you may need to adjust colors)

> SUBJECT: Click to sign into your account

Hi, there!

Let's get you signed into your Open Access Button account. 

```
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
      <table border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td align="center" style="-webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px;" bgcolor="#e9703e"><a href="https://litmus.com" target="_blank" style="font-size: 16px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; text-decoration: none; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; padding: 12px 18px; border: 1px solid #e9703e; display: inline-block;">Click here to login &rarr;</a></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

Or enter this code on the login page: xxxxxx

The code and link is valid for 30 minutes, so be sure to use it soon!

We look forward to getting you access to research,

The Open Access Button team

#### However

A signup email is something we should certainly do, and @markmacgillivray, I'm wondering if we can drive that from when people finish their account details? People should only do that once, and so is much better suited to copy like the above.

**Comment by chealsye** [comment]
Yes, this is the copy I am suggesting for when people sign up. When I sent you the drafts you told me to add them to github. 

Simpler is fine. But this is the current email being used is the following:

![screen shot 2016-10-17 at 08 19 38](https://cloud.githubusercontent.com/assets/9299248/19458502/7e07fab8-949a-11e6-87b4-9c27529c37db.png)

I included what I did, because it's been used for a few months, a year? I thought this information needed to be in here. 

Our login email has always included other information - I was following our practice. I think "authenticate your account" is a lot more specific than "confirm your email." I was attempting to make this email more friendly, make people want to use it. Per Joe's instruction I read through a lot of welcome emails to try to create a welcoming tone while still including what I thought was required information. This copy, including the subject line, all had thought out purpose.

It's really insulting to be lectured at about what a login email should and shouldn't include when the login email we've been using doesn't follow any of those rules. I tweaked the standard one of you set. 

Simple is good. I love simple and the other copy is fine.

**Comment by markmacgillivray** [comment]
I don't care what the copy is. It is not intended as insult when I give commentary on what would work better. It does not preclude any of your reasoning for having added or changed something, from a version that I did not write in the first place - the intent of writing copy now is to make things better, not for it to be what it was, or to be what I prefer, or to be overriding what you suggested. If you take commentary as insult, I will simply stop providing commentary. I will stick only to functionality, and will stop trying to make any helpful changes to how copy should fit with functionality. Trying to add helpful commentary and being told that my help is insulting is not conducive to good teamwork.

I will finish the templates in the emails folder of oab_static based on the content that I had made available to me previously, I will test that the emails work, and then I will leave it to you to make whatever copy in them that you want. Unassigning myself from this one.

**Comment by markmacgillivray** [comment]
Actually, come to think of it, putting all that content into email templates is probably not something I should do - now that I rethink it, it sounds like an attempt by me to state what content should be in an email template. I will finish the example one, and share that, and leave the writing of any other email template content to other people, so that I am less likely to be unintentionally insulting.

**Comment by JosephMcArthur** [comment]
* I have put in a login email template here: https://github.com/OAButton/oab_static/blob/develop/emails/login.txt. Mark, I didn't see variables for the codes & login links. @markmacgillivray can you slot those in? 

* I have a template for an email that should be sent when a user fills in their account details (username / full name / affiliation etc): https://github.com/OAButton/oab_static/blob/develop/emails/account%20completed.txt. @markmacgillivray can that be driven by a successful "save details" at sign up? 

* @markmacgillivray are the blank templates you've left here the only emails left that the system is currently sending?

**Comment by markmacgillivray** [comment]
The system is not currently sending any emails. The templates that are blank are ones that I started doing but then decided against it. They could be triggered by certain events, as their names roughly indicate, and there are other such events that could trigger things too.

For the two that you have created, is it OK to edit their content at all or should I use them exactly as is without change or comment?

**Comment by JosephMcArthur** [comment]
Login email should have all the links needed. @markmacgillivray you should be good to switch this out for the current email. 

- [ ] put in login email

Some things I thought about while putting in the links & copy but don't need to be changed right now:

* I put "open access button" in the email subject so that the email stands out. Can reverse. 
* "we look forward" line suggests we haven't yet done that, and that the task they're logging in for is the do this. Both of those might not be the case.  
* we can have their email used instead of "there". Personally, I often forget what emails I sign up to services with so it's helpful for me to have this in the first email (yes you can see it from the sending address, but this is a smidge easier). 
* the "please confirm your email" line is great for the first time, but afterwards isn't 100% right. It's more just about confirming you're the person who should be able to access the account but I can't for the life of me think about another way to phrase it. 

Also, just chatted with Chealsye offline. We're being strategically lazy here and adopting a policy of "only send where a user should take action & that isn't indicated on screen" until further notice. Having a email on sign up completion falls foul of this rule. 

What means is that once the login email is on dev we're good to close.

**Comment by chealsye** [comment]
-It's fine. 
- What sign off do you want instead? The point of the Button is to get them research. Yes, there are going to be outliers that are just curious or people who successfully got an article through the browser but now are signing up to complete a request, so, sure, it's been done... but do you want some generic valediction?
-That's fine.
-No, it isn't 100% right. But the signup and login page is the exact same unfortunately -- how is the Button supposed to know the difference?

**Comment by JosephMcArthur** [comment]
Closing for now so we can track biggest issues. This seems a-okay for now. Reopen if needed.

**Comment by JosephMcArthur** [comment]
reopening until we have the email tested

**Comment by JosephMcArthur** [comment]
FYI, this now now being send from admin. Now emails will come from either admin or requests.

**Comment by markmacgillivray** [comment]
Signup email now uses new template, tested and works
