### ISSUE TITLE
Change "Contribute to requests" to "Support Requests" in the website header

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#296]
@JosephMcArthur - We decided on support, right?

**Comment by JosephMcArthur** [comment]
Sure. Have also changed download to sign up, as there isn't actually anything being downloaded.

**Comment by chealsye** [comment]
@JosephMcArthur the requests isn't capitalised. Could you change it to Support Requests?

**Comment by JosephMcArthur** [comment]
yes, done.
