### ISSUE TITLE
The wonderful world of email templates

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/backend#298]
Particularly for @chealsye and @JosephMcArthur whilst progressing through the email templates functionality today, I have some overarching questions for us to consider, not about one specific template or one specific functionality, so I will put them all here in one issue, so we can quickly get answers.

I may add more questions as comments as I proceed.

1. is it necessary to email a user when they just created a request, if the request has all the info we need to action it? If we do need some missing info we certainly will email them, but if we don't, then it seems unnecessary - because they will already know they just created it, they will be given the link, and have it opened for them too. So I think perhaps we should just email if there is missing info. That way a user knows if they get those emails in their inbox that there is action to take, and that they are not just notifications, so they could use them as reminders of ones they need to update later, if for some reason they do not immediately have time.

2. when support is added to a request, should we email the request creator and/or the contact author every time? That could get a bit extreme if any requests get very popular. Unfortunately it is also hard to be able to just send an email say every 10 requests, or every day/week with an update of how many new ones there are, because we cannot know what the count was the last time an email was sent. Adding that kind of tracking would take a long time. What we can do, as an alternative though, is to know that a request has changed in SOME way since last day/week (however long we want to wait before sending an update), and if there has been a change we can say "this request has had more support since last X". Is that OK? I think it is the best option, rather than potentially bombarding people.

3. When informing every supporter that a request is successful, can we send a generic email to them all, sent in bcc? Otherwise we risk (if we are very successful) sending thousands of individual emails to each supporter, which could quickly swamp our mail handler. We can send 10000 a month for free anyway, and can pay for more, but I would rather code it more efficiently in the first place if this is acceptable.

4. I am making templates based on what the system currently sends, and on a possibly old copy of what were the email drafts from a google doc at some point in the past, not sure when. Some changes may be necessary due to fitting things into how the functional flow goes, but assuming I make a bunch of templates and attach them to functionality, are you both happy that some tweaks will need to be made to the content, and some emails may merge/disappear? Once I have the code at a ready state, you could go through the templates I create and see how I used the variables, and can change the content as you think is necessary. If a need seems to come up for an email we don't yet have, we can discuss how to fit that into the functionality. (In future, once we have the fundamentals of the system in place, it should be quite easy to do this when we think of new email needs.)

**Comment by JosephMcArthur** [comment]
1. This makes sense for now. 
2. Makes sense.
3. Generic email is a-okay
4. Great.

**Comment by markmacgillivray** [comment]
example.txt and author_request.txt both now in the emails folder of oab_static, describing principles discussed above. Specific questions on what emails should exist and when they should be triggered will now be driven by the issues that are about the particular emails in question.
