### ISSUE TITLE
When user is signed in, remove sign-up box (and maybe put in /request/new box)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#300]
On the frontpage the sign-up box still appears even when you're signed up. 

Would be nice if this disappeared & it's place you could just have /request/new. 

This feedback comes from a user test @meganwaps did. Great work.

**Comment by markmacgillivray** [comment]
Can hide the signup, but if /request/new is going to allow people to search
without being logged in, it won't make so much sense to only show that when
logged in.

**Comment by JosephMcArthur** [comment]
I think it's just a nice touch in this case, I agree that with the info we
have now it doesn't make sense to only display if logged in!

Something to think about later on.

**Comment by markmacgillivray** [comment]
Done
