### ISSUE TITLE
For requests that need help, add a specific cta on the request page for what is missing

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/backend#306]
Also, having loaded the old requests, it seems that the email may exist but be zero length, so ensure the email box shows and can be edited into

**Comment by markmacgillivray** [comment]
Made this more obvious, and controlled what can be shown depending on status and user

**Comment by JosephMcArthur** [comment]
reopening as @chealsye needs to make / approve copy for this

**Comment by JosephMcArthur** [comment]
@markmacgillivray ironically it's unclear here what actually needs help

![image](https://cloud.githubusercontent.com/assets/4953703/19626827/5496ca6a-9931-11e6-9a65-72874581933d.png)

**Comment by JosephMcArthur** [comment]
Prompt changed to 

> We need a bit more information for this request. Can you look at the details and fill in what's missing?

**Comment by JosephMcArthur** [comment]
Closing to keep track of key areas, but reopen if needed @chealsye
