### ISSUE TITLE
Wait to display install / getting started options until after account details are completed

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#307]
Not sure if this is a good idea or not. Thoughts @markmacgillivray / @chealsye / @meganwaps

**Comment by chealsye** [comment]
I think it makes the most sense to display the installation options after they complete their account details. One step at a time.

**Comment by markmacgillivray** [comment]
I think it better to keep the instructions on the instructions page, and
not on the account page at all. When the user has completed their account
details and sees buttons for relevant plugins etc, we can have a button
there too that goes to the instructions page. No need for duplication.

**Comment by markmacgillivray** [comment]
OK this has been changed to only show after the user has provided their details. I think that is all that is left on this issue so I am closing, but re-open if anything outstanding.

**Comment by JosephMcArthur** [comment]
the section doesn't come up without refreshing, which clearly isn't workable. untill this is fixed we have to move this back to 3.5

**Comment by markmacgillivray** [comment]
Changed it to show after save too.

**Comment by JosephMcArthur** [comment]
ahem. 

![image](https://cloud.githubusercontent.com/assets/4953703/19649110/70e57cc2-99fc-11e6-9901-3208613adaba.png)

**Comment by JosephMcArthur** [comment]
okay the page was just super odd for me. Going to try a private browser.

**Comment by JosephMcArthur** [comment]
@markmacgillivray  okay, save details now doesn't work for me

**Comment by markmacgillivray** [comment]
I hid them for after logout now too. Save button works fine for me

**Comment by markmacgillivray** [comment]
Unassigning myself, nothing else I can do here - @JosephMcArthur maybe you want to get someone to do some more testing of this page

**Comment by JosephMcArthur** [comment]
This is working well for me now. But just in case...
@meganwaps @svmelton @natalianorori can you try and sign up with new accounts (just put a +1 on your email if you've already used it).

**Comment by svmelton** [comment]
It works well for me.

**Comment by meganwaps** [comment]
This is working fine for me as well.

**Comment by JosephMcArthur** [comment]
Great, this is done then.

**Comment by markmacgillivray** [comment]
This page already had functionality to control what content was shown when
- is something now displaying when you don't want it to? The install
options did not show until signup had been completed - is this no longer
the case?

**Comment by natalianorori** [comment]
Just tried and worked for me as well!
