### ISSUE TITLE
When asked to sign in to make a request from /request/new you have to re-enter your details once you have sign in

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#308]
Would be much easier if it remembered

**Comment by JosephMcArthur** [comment]
have assigned this for the next milestone, but realise it might be hard. An estimate of difficulty would be useful.

**Comment by markmacgillivray** [comment]
You do if you follow the link rather than use the code, yes. I have thought
about passing the data through cookies, which may work, but have not tried
yet. However because we have cookie management already in the login app, it
may be simple if it works. But it's a matter of whether I have time to get
to it or not, so next milestone is fine for now.

**Comment by markmacgillivray** [comment]
What pop up?

**Comment by JosephMcArthur** [comment]
The info bar allowing users to go back to the page they were on

**Comment by markmacgillivray** [comment]
Popup no longer shows if account not yet complete. Request page also checks for values and redirects if not present. Still an issue to make it possible to work by cookie when someone follows the link url

**Comment by JosephMcArthur** [comment]
Copy for this message was:

> Thanks for signing in. Click here to return to the page you were viewing

but due to #328 the first sentence wouldn't apply in some cases. I've changed it, but @chealsye if you don't agree or want something different entirely do say.

**Comment by markmacgillivray** [comment]
Note that functionality has already changed to only show that message after the user has completed their details

**Comment by markmacgillivray** [comment]
This has been enhanced now, was a bit more complicated than expected, but I have tested it too. @meganwaps I will assign to you now, to check it works as planned.

You should now find that if a user on the dev site goes to a page like the new request page and the do a search to find something, if they are not logged in they will be asked to log in to create a request, just as they were before. But now, once they login they should be immediately redirected back to the new request page that they were on, even if they log in by clicking the link from their email, and also if they log in by typing in the code to the page. If they are a new user who still needs to fill in some details when they log in, then they will be asked to complete the details. Once they are complete, then they should see a message at the top of the screen that they can click to go back to the new request page they were on.

**Comment by JosephMcArthur** [comment]
Okay, tested on chrome & safari with a finished account. Works wonderfully. 

However, I can do this with an account that doesn't have full info. But I also am having trouble making an account on dev atm. @markmacgillivray

**Comment by markmacgillivray** [comment]
@JosephMcArthur I just made an account on test no problem, no errors on the backend. What trouble did you have?

**Comment by JosephMcArthur** [comment]
Okay, I just did hard refresh on chrome & making accounts normally went okay. 

Making them after clicking "complete your account" on /request/new didn't work. Hitting save details led to no action. I had the URL http://oab.test.cottagelabs.com/account?next=%2Frequest%2Fnew%3Furl%3Dhttp%3A%2F%2Fscience.sciencemag.org%2Fcontent%2F293%2F5530%2F629%23

**Comment by markmacgillivray** [comment]
I just tested this again, and works fine with a new account, and the link takes me back to the /request/new page for the URL I was checking, as expected. Maybe your usage just coincided with development taking the backend down at that time? Can you try again?

**Comment by JosephMcArthur** [comment]
Okay, I got most of the way (managed to sign up okay) but then landed on a 404 with the following URL. 

http://oab.test.cottagelabs.com/%2Frequest%2Fnew%3Furl%3Dscience.sciencemag.org%2Fcontent%2F293%2F5530%2F629%23

I think you're changing the URL of those pages though... so probably transient.

**Comment by markmacgillivray** [comment]
Hmm. That URL is wrong, and not in a way that I am expecting. I will have another look. What browser did you use?

**Comment by JosephMcArthur** [comment]
chrome, mac.

**Comment by markmacgillivray** [comment]
Should affiliation be required? I think the error is because it is not required on the account signup, but is expected by the new request checker. We will have accounts that have not required it, I think. I will change it to not be expected at new request either, and will fix the URL redirect.

**Comment by JosephMcArthur** [comment]
Well, now I think it does need to be required. But that creates challenges
for people without affiliations that we don't have a smooth way of
handling.

I've been thinking that our sign up fields aren't all that well thought
through recently (given new strategies), perhaps it's time for a rethink.
For example, the username / full name split feels like something we could
lose now (for example we could just display first names where we currently
show usernames). The user types also confuse a lot of people (I've had many
people say that they don't identify with any) and cause issues with the
request system. The obvious issue is that changing that with a bunch of old
users makes the data messy etc.

**Comment by markmacgillivray** [comment]
I think for now to get this closed we should leave it not required. Later followup with users to collect more data could be a good approach. Also, requiring less encourages more signup.
