### ISSUE TITLE
when not logged in, display a message that's responsive to what's available on /request/new

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#309]
e.g So if the article is available, ask if you want the data.

This probably just needs to happen in the headline. 

#### Article found

> The data isn't available, but you can create a request!

#### Data found

> The article isn't available, but you can create a request!

#### Neither found

> The research you need isn't available, but you can create a request!

This works well if you're logged in, but doesn't if you're not

**Comment by markmacgillivray** [comment]
Changed.
