### ISSUE TITLE
Bullet points formatting extremely poorly on mobile (and oddly on desktop)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#312]
They seem to hang to the left of their container. 
### Desktop

e.g http://oab.test.cottagelabs.com/terms
### Mobile

![screenshot_20161019-221049](https://cloud.githubusercontent.com/assets/4953703/19537769/237bd38e-9649-11e6-912f-1640333f343b.png)

**Comment by markmacgillivray** [comment]
Fixed. For unknown reasons, the site css that had been added to the old site, and was copied across for the new site, had this in it. I don't know why whoever added it to the old site css in the first place did so, there were a few oddities on there after various people worked on it. Removed now. If it was used to make something work on those page with all the cards etc, and if that code is still based on something old too, then they may now not be as expected. But as I do not know what the original intent / expectation was, I cannot check that. Closing this issue, seems resolved.

**Comment by JosephMcArthur** [comment]
Still seeing the bug for numbers

**Comment by JosephMcArthur** [comment]
realising I didn't specifc numbers above, it's in the phone, but of course it's hard to see due to the error itself!

**Comment by markmacgillivray** [comment]
It does now work for me, just sent you a screengrab. Can you check you're seeing the newest page? Add ?1=2 to the url

**Comment by JosephMcArthur** [comment]
Sorry, you're right! Thought I'd hard refresh but potentially not.

**Comment by JosephMcArthur** [comment]
seems to be back only on mobile, not just small screen.

**Comment by JosephMcArthur** [comment]
@meganwaps @chealsye @svmelton @natalianorori can you check the formatting of bullets on oab.test.cottagelabs.com/about#press?

**Comment by chealsye** [comment]
The bullets look fine to me. There are some parts of the images section I should have already done -- I'll get it done sometime today.

**Comment by svmelton** [comment]
The bullets look fine to me on mobile, full, and small screen on Chrome, Safari, and Firefox.

**Comment by JosephMcArthur** [comment]
Thanks folks, this appears to be a personal issue on my end!

**Comment by natalianorori** [comment]
Just checked on my phone and they are displaying poorly. Bullets on top of each other and little to no space between the points.

**Comment by chealsye** [comment]
Hmm. I checked the site on my phone again and it looks normal although the bullets get cut off a bit, but all formatted quite well. But it is concerning you both are having issues and likely some users will, too...

**Comment by JosephMcArthur** [comment]
@natalianorori & @chealsye screenshots please. 

Reopening while we look into this.

**Comment by markmacgillivray** [comment]
Note that it is possible to spend forever looking for layout inconsistencies across all devices and all browsers. Given that we know it appears as expected, even in some cases for the same people who are seeing it wrong some of the time but not all the time, I'd say don't worry too much about this sort of thing.

**Comment by chealsye** [comment]
![screenshot_20161026-074200](https://cloud.githubusercontent.com/assets/9299248/19726742/6302cfec-9b5a-11e6-9bc7-b7394044185b.png)

The bullets get partially cut off.

**Comment by natalianorori** [comment]
Just checked again from my desktop and phone and they're displaying normally for me this time

**Comment by natalianorori** [comment]
It's looking fine for me now

**Comment by meganwaps** [comment]
I cannot see everything at once in the bullet portion, but I can easily maneuver to see/read everything.
![image](https://cloud.githubusercontent.com/assets/5968703/19735753/b884953e-9b61-11e6-8949-e2e0e73566b1.jpg)

**Comment by JosephMcArthur** [comment]
Can you test the scale of this issue on Browserstack please? Just try & replicate and see how many devices it affects

**Comment by JosephMcArthur** [comment]
@chealsye, have we heard complaints about this? If yes, please open this, if not, closing for now. This seems minor at best and is going to require time we could spend elsewhere to fix.

**Comment by chealsye** [comment]
There have been no complains on social media, but I'm not sure if we've received any emails or bug complaints.
