### ISSUE TITLE
Plugin Copy changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#319]
This is a holding issue to catch bits of plugin copy that may need adjusting

#### Shown when you first open ii & haven't visited /account

> You don't appear to be signed up yet! If you sign up you can create and support requests, and more. Please signup or login now, and your API key will be automatically retrieved.

**Comment by JosephMcArthur** [comment]
#### on total error of api 

> Sorry, something went wrong with the API.

#### when someone else has started a request

> There is an open request for this ' + type + '. Add your support. 

#### when a request has been made successfully 

>Thanks very much for create/creat/support/ing this request! Please take a moment to go and view the request, and provide any additional support that you can.
We have opened it up in a new tab for you. If your browser blocked it, you can open it here.

**Comment by JosephMcArthur** [comment]
#### submit box (at zero words)

> Tell us your story in up to 25 words to support this request

I'm wondering if here we shouldn't call it a story anymore? That's a bit odd, no?. "reason" might be clearer to a broad segment of people. That is essentially what we're asking for here.

**Comment by JosephMcArthur** [comment]
#### Total error code pictured I think

<img width="374" alt="screenshot 2016-10-23 00 32 51" src="https://cloud.githubusercontent.com/assets/4953703/19623187/5b118bec-98b8-11e6-8438-1b5009a54fcb.png">

**Comment by JosephMcArthur** [comment]
#### go to instructions page 

The error screenshots would all look as the screenshot you already added to #319 - the only difference is the text. Here are the current texts:

BLACKLISTED (THE WORD instructions IS A LINK TO /instructions):
Sorry, the page you are on is not one that we can check availability for. See the instructions for help.

UNAUTHORISED:
Unauthorised - check your API key is valid. Go to ACCOUNT_URL and sign up if you have not already done so. Once you are signed in the plugin should find your API key for you.

FORBIDDEN:
Forbidden - please file a bug.

UNKNOWN ERROR:
Sorry, unknown error, perhaps the system is offline, or you are offline. Please file a bug including this code: ERROR_CODE

**Comment by JosephMcArthur** [comment]
#### when you make a request

> Thanks very much for creating this request!
Please take a moment to go and view the request, and provide any additional support that you can.
We have opened it up in a new tab for you. If your browser blocked it, you can open it here

Here goes to the request page

**Comment by JosephMcArthur** [comment]
Okay, lots of alternatives to be put in. 

> You don't appear to be signed up yet! If you sign up you can create and support requests, and more. Please signup or login now, and your API key will be automatically retrieved.

to 

- [ ] > some test

**Comment by JosephMcArthur** [comment]
Am currently putting these in... please hold any changes

**Comment by JosephMcArthur** [comment]
Okay, all the changes are in a PR here as I don't want to count on my coding skills here. 

@markmacgillivray would appreciate a review before merging. https://github.com/OAButton/unified-extension/pull/27/files

**Comment by JosephMcArthur** [comment]
- [ ] @markmacgillivray can you remove the request id number from the message a user sees when they're clicking on their own request? It's line 156 of main.js

**Comment by markmacgillivray** [comment]
Done and pulled PR, closing issue
