### ISSUE TITLE
Spinner on pluggin is pixelated

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#320]
It can also take a few seconds, and I can see that making people worried. 

I wonder if a bit of copy here would be a good move. So you'd have the spinner and 

> We're looking! Give us a moment. 

@chealsye any thoughts?

**Comment by chealsye** [comment]
Why is it pixelated? If you need a different size, let me know.

That bit of copy is fine.

**Comment by markmacgillivray** [comment]
I couldn't use the orange one so I scaled up the small grey one that I had
already used on the website. The orange one does not spin, and the image
did not respond to CSS instructions to spin it. I'd need that orange one
turned into an animated gif to be able to use it. I can make a larger scale
of the grey one anyway, so I'll use that if we can't get a spinning orange
one.

**Comment by markmacgillivray** [comment]
New one made.
