### ISSUE TITLE
Plugin didn't take API Key

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#321]
### Expected Behavior

Plugin accepting API key, and getting a confirmation message

### Actual Behavior

account page seems to not send the key, I get no confirmation message & can't save details. 

Am told
>You have your plugin installed! Just checking your API key is set for you...

### Steps to Reproduce this bug

* Hardware versions: Mac
* Software versions: Chrome
* Steps to reproduce:

 1. Download plugin
 2. Open it on an article or two
 3. Go to account page. Have logged in but not completed sign up.

On refresh, I was able to complete sign up. But couldn't get it to sign in.

**Comment by JosephMcArthur** [comment]
just corrected the dev site URL in the plugin, but still couldn't make it work. Have seen there is a message in there as follows:

> Your API key could not be found!

But that has yet to display.

**Comment by markmacgillivray** [comment]
Someone has commented out the chromeinstall div - without it, the plugin errors out. Why does it need to be commented out?

**Comment by JosephMcArthur** [comment]
fixed. But now buttons are back.

**Comment by JosephMcArthur** [comment]
That was me! Just didn't want the button to show on the test site yet (as
it would lead to the old plugin atm which we don't want folks to use)

**Comment by markmacgillivray** [comment]
I think this issue has become obsolete anyway, since further changes have been made - the buttons are there and show when expected, and we now know how to hide the plugin button in a way that does not break the page. So now that the earlier error does not occur, the api key matching should be reached fine, as it appears to be.
