### ISSUE TITLE
Plugin text fonts & size

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#323]
The header looks right, the body text doesn't. May also want to increase font sizes.

**Comment by JosephMcArthur** [comment]
body should be roboto

**Comment by markmacgillivray** [comment]
I don't think we can use google web fonts in the extension. Roboto is one of those, not sure about Monserrat. Font size increased. Font is sans serif throughout though, so looks similar to site. Is this OK? Assigning back to Joe to confirm and close if OK.

**Comment by JosephMcArthur** [comment]
Just glanced, looks fine & if we can't do any better then so be it! Certainly a bit improvement.
