### ISSUE TITLE
Copy & Screenshots for the chrome store

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#325]

**Comment by JosephMcArthur** [comment]
@chealsye in case you're in any doubt, the plugin now looks like what the plugin will look like.

**Comment by chealsye** [comment]
Screenshots

![screen shot 2016-10-23 at 22 12 57](https://cloud.githubusercontent.com/assets/9299248/19632226/9a19a620-9972-11e6-8282-8279a780d5c2.png)

![screen shot 2016-10-23 at 22 40 23](https://cloud.githubusercontent.com/assets/9299248/19632231/a0a9553a-9972-11e6-8e9e-e9f33afcd216.png)

![screen shot 2016-10-23 at 22 39 51](https://cloud.githubusercontent.com/assets/9299248/19632243/b6e2ae6e-9972-11e6-8bb8-db96c5e97369.png)

![screen shot 2016-10-23 at 22 13 45](https://cloud.githubusercontent.com/assets/9299248/19632249/be5c4646-9972-11e6-87bf-a77953d26b12.png)

**Comment by chealsye** [comment]
Copy


> **Get the articles and data you need
> with the Open Access Button.**
> 
> The next time you can't access the research you need, use the Open Access Button. The Button searches thousands of sources to get you instant, legal access to articles. 
> 
> If the article or dataset you need is not available, you can create a request for the research. Requests are sent to the author. The Open Access Button's request system is transparent and encourages authors to make their research openly available, so you can get the research you need. 

@JosephMcArthur Good to close unless you want some edits

**Comment by JosephMcArthur** [comment]
Chealsye, do we have images at this size too:
- [ ] Small tile - 440x280:
- [ ] Upload new imageLarge tile - 920x680: (optional)
- [ ] Upload new imageMarquee - 1400x560: (optional)

**Comment by markmacgillivray** [comment]
@JosephMcArthur I published the new plugin on chrome store as requested last night, but it does not appear to have these images etc yet.

**Comment by chealsye** [comment]
440x280

![plugin_440](https://cloud.githubusercontent.com/assets/9299248/19860497/466219ac-9f5f-11e6-92af-c62be3575a6e.png)
![screenshot1_440](https://cloud.githubusercontent.com/assets/9299248/19860499/46738cc8-9f5f-11e6-8081-f2bb5fa6fdec.png)
![paywall2_440_stretch](https://cloud.githubusercontent.com/assets/9299248/19860502/49ca4fa6-9f5f-11e6-9937-acb782715ecf.png)
![paywall2_440](https://cloud.githubusercontent.com/assets/9299248/19860501/49c6a39c-9f5f-11e6-9f92-e85fd62e7c04.png)

**Comment by chealsye** [comment]
Here's a 920 of the plugin
![pluginrequest_920](https://cloud.githubusercontent.com/assets/9299248/19862077/47580a96-9f65-11e6-8d42-675df6fe795c.png)

Here's a marquee size
![buttonmarqueechrome_1400](https://cloud.githubusercontent.com/assets/9299248/19862078/4a5c2ca4-9f65-11e6-82ee-39dfaa26d92e.png)

I don't think its ~amazing~ but I have limited time today. Can make something else if you have another idea. I have two small grants to finish today and tomorrow, but will be more available come Wednesday.

**Comment by JosephMcArthur** [comment]
Can we get one at 1280x800 too please? 

Some notes on that from the store:

>We prefer screenshots to be 1280x800 pixels in size, as they will be used in future high dpi displays. Currently, the Chrome Web Store will downscale all screenshots to 640x400, so if your screenshots will not look good downscaled (eg. have a lot of text) or if 1280x800 is too big for your app (screenshot of low resolution game), we also support 640x400 pixels screenshots.

**Comment by chealsye** [comment]
![request_1280x800](https://cloud.githubusercontent.com/assets/9299248/19993458/436a2658-a21c-11e6-98e8-01e1e0cc2d41.png)

Here's this one at 1280x800.

I tried doing other things with that size, incorporating different stages of the Button... but it looked awful. Like a messy collage. :/

**Comment by JosephMcArthur** [comment]
this is up!
