### ISSUE TITLE
On restart, plugin stops other plugins appearing

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#326]
This may be an artefact of all dev plugins, would seem reasonable, but logging none the less. 

### Expected Behaviour

* all plugins load at once

### Actual Behavior

* our plugin appears with a orange background around the icon
* removing the plugin allows other plugins to appear

### Steps to Reproduce this bug
*Please include any info about the version of the tool you're using and your system. - remove this note before posting*

* Hardware versions: mac
* Software versions: chrome
* Steps to reproduce:

 1. download plugin
 2. restart computer
 3. start chrome

**Comment by markmacgillivray** [comment]
Can't recreate this. Mine all come in as normal.

**Comment by markmacgillivray** [comment]
Tried this on my linux machine and on mac, still can't recreate.

**Comment by markmacgillivray** [comment]
I'll assign this back to @JosephMcArthur - you'll need to screengrab it, or talk to me about it at some point, as I can't replicate.

**Comment by JosephMcArthur** [comment]
Okay, it seems the orange background may be expected: http://stackoverflow.com/questions/22551316/chrome-extension-icon-has-a-yellow-orange-highlighted-background-border

**Comment by markmacgillivray** [comment]
Weird it doesn't do it on mine, I could be using an old browser. But if it is from 2013... anyway if it is expected, and yes the description does seem to match what you experienced, then we can close this I think

**Comment by JosephMcArthur** [comment]
Would be great if @meganwaps @chealsye @natalianorori could try and recreate this.

**Comment by markmacgillivray** [comment]
Ah ha, this does happen now on my mac, probably a newer version. So yes, it goes orange and shows a warning about developer extensions, which I accept, then it loads the other extensions and the colour goes back to normal. This is OK, just the dev extension warning which won't show up once it is installed normally.

**Comment by JosephMcArthur** [comment]
Great, closing.
