### ISSUE TITLE
make stories on request pages not required

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#327]
from @meganwaps user test today with NA

**Comment by markmacgillivray** [comment]
I'm confused by this - do you mean when creating a new request, or when adding support to an already existing request? In each case I thought stories ARE required, and I am not sure where it says they are not.

**Comment by JosephMcArthur** [comment]
Sorry, this is 100% not clear enough. When adding support, leaving a story should be optional.

**Comment by JosephMcArthur** [comment]
We may want to expand the "optional" note a bit to say something like:

> This is optional, however it will help the request get fulfilled.

**Comment by markmacgillivray** [comment]
Done
