### ISSUE TITLE
Don't allow user to make a request without completing all sign up details

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#328]
User test with NA showed this can happen. The point of getting people to sign in / up is as we need those details to do a request.

**Comment by markmacgillivray** [comment]
Have tried adding to this, but must be tested before going live

**Comment by markmacgillivray** [comment]
As in it works for me, but do we need more user testing? Someone should have a go at least. Will assign to @JosephMcArthur ;)

**Comment by JosephMcArthur** [comment]
This seems to work, but needs copy @chealsye 


#### text
> Hey, sorry, thanks for signing up, but we still need a bit more info from you before you can create requests - could you go to your account page and provide it for us? Thanks!

#### button

> Complete your account details

**Comment by JosephMcArthur** [comment]
This isn't working on the plugin & I expect bookmarklet

**Comment by markmacgillivray** [comment]
This is impossible to control at the plugin or bookmarklet. We can hide the links so that a user cannot GET either of those things until after they provide their full details (which, as I mentioned before, is how the account page worked until someone changed it. But, someone could still get the plugin from the chrome store, sign up, not complete those fields, and still submit a request. the best we could do is that I could have the backend refuse the request, but there is no way to tell the user why that happened. A new requirement for being able to pass error (and other) messages to the plugin for display to the user has been raised this weekend, but there is no time to do that for a release tomorrow.

@JosephMcArthur  We either move this issue to a later milestone, or delay the release.

**Comment by JosephMcArthur** [comment]
> as I mentioned before, is how the account page worked until someone changed it. 

I'm not sure when it was like this, but I'm all for it going back. I think I've made that clear in #307 which is in the next milestone. 

> A new requirement for being able to pass error (and other) messages to the plugin for display to the user has been raised this weekend

Hopefully, this isn't how my request earlier came across. All I want is for the error code displayed to not be 0. 

We can move this to a later milestone & address then. I expect we can let a user make it, and ask them to finish sign up later.

**Comment by JosephMcArthur** [comment]
moving here as we should fix copy.

**Comment by JosephMcArthur** [comment]
current text 

> We need a few more details about you before you can make this request. Can you take a second to finish signing up <a href = "/account">here</a>?

**Comment by JosephMcArthur** [comment]
Okay, we can address this without new plugin requirements by catching it during moderation. 

- [ ] catch in moderation
@natalianorori you will need to keep an eye out for this, it will look like emails not having user details in preview. This needs to go in the moderation guide

- [ ] fix in moderation
@chealsye you make an email that can be sent asking users to go to their account page & fill in details. 

- [ ] fix on request page
@markmacgillivray, not saying we _should_ do this. Just wondering if we can have a message on their request page which tells them to go to the account (since we're sending them there anyway). That helps keep the plugin simple & lets the user get their stuff done. 

The above can close this issue until we get more data on how large an issue it is.

**Comment by markmacgillivray** [comment]
There is currently no functionality on the request page to allow for the user details to be added later. Also, having the user add them to their account later will not populate them into requests they have already made. All these things could be done, but they are no more simple than the option of not allowing them to make one unless they have completed details. This should already be impossible from the new request page, but could be done from the plugin, in the situation that a user goes to the sign up page but does not bother completing all those details, but does get the plugin direct from the chrome store themselves.

So there are many solutions, but none that take no work. It just has to be scheduled into later sprints at some point.

**Comment by JosephMcArthur** [comment]
Okay, given the new hiding of the plugin download box while users sign up I don't think the above is likely to happen. 

Bigger fish to fry, closing for now. If @natalianorori sees issues in real requests, we can address.

**Comment by natalianorori** [comment]
I'll keep an eye for this during moderation of real requests, and add a note about it on the manual

**Comment by markmacgillivray** [comment]
Again this is odd, if you mean the user is signing up but seeing the link
back to the request, that did not happen previously. The content must have
been edited in ways that has broken this. Either that, or the user signed
up and then manually went back to the new request page without filling in
all their details - in which case there is nothing we can do to stop them.
I could add a check to the new request page that not only checks they are
logged in but that they have provided those details, but that is additional
functionality we do not have yet. Needs clarification.
