### ISSUE TITLE
background on cogs isn't transparent 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#330]
<img width="374" alt="screenshot 2016-10-23 00 32 51" src="https://cloud.githubusercontent.com/assets/4953703/19623250/6debf818-98ba-11e6-9bea-0bc03f93bb77.png">

**Comment by markmacgillivray** [comment]
Actually it is, but for some reason I can't get it to show any better than that. If anyone with better design skills can make a better version, please do so. I'll unassign myself, but reassign if I am needed to add it into the code.

**Comment by JosephMcArthur** [comment]
getting this now

**Comment by JosephMcArthur** [comment]
Ta-da (again)

![icon_broken](https://cloud.githubusercontent.com/assets/4953703/19628506/f64458c6-9956-11e6-81ee-e966088638f8.png)

**Comment by markmacgillivray** [comment]
Cool, fixed
