### ISSUE TITLE
Error codes don't seem that helpful for user or us

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#331]
Are they functional in any way? I've only seen 0, which "feels" like it's not real.

**Comment by markmacgillivray** [comment]
We don't expect users to often see errors, but if they do, it is worth knowing the code. However if it does not fit with copy preferences, it can be removed.

**Comment by JosephMcArthur** [comment]
It's not so much I'm averse to showing a code. It's just that 0 as an error code doesn't feel real. I know it's silly, but 321 would feel more real.

**Comment by markmacgillivray** [comment]
Removed codes, show link to bug page instead.
