### ISSUE TITLE
make text on plugin buttons appropriate when find system throws back different response

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#338]

**Comment by markmacgillivray** [comment]
Fixed

**Comment by JosephMcArthur** [comment]
Need to check that this will adapt when we're asking them to support a request

**Comment by JosephMcArthur** [comment]
Should be 

> support request. 

Is this also fixed on the bookmarklet?

**Comment by markmacgillivray** [comment]
This is ambiguous though - support article or support data is possible. Is that OK to use instead?

**Comment by JosephMcArthur** [comment]
I think support article / data is worse, you can't support an article. 

> Support Article / Data Request 

To my taste adding the extra word with the icons isn't needed, but for the sake of a word better to be clear than allow for misunderstanding.

**Comment by markmacgillivray** [comment]
That will make the wording longer than the size we have to fit it in though, at current font sizes. It is harder to autoscale the size of those buttons because of the layout. Putting in too many words will make it look bad. If saying "support request" is good enough, that kind of undermines the point of having text in those buttons in the first place - e.g. if it is obvious from the icon what they are about, then the wording is superfluous.

**Comment by markmacgillivray** [comment]
For now I have gone with starting out at "Unavailable". If there is a request it will say "Support TYPE" unless the user has no api key, in which case it still says unavailable and they are seeing the sign up message anyway. If there are no requests and user is not signed up it stays at "Unavailable" but if the user is signed up it changes to "Request TYPE".

**Comment by markmacgillivray** [comment]
I'll unassign to track other issues needing doing, reassign if there is a workable alternative.

**Comment by JosephMcArthur** [comment]
Just chatted online briefly (we thought we weren't getting each other here. 

* unavailable text is staying as we need to make clear to the user that the button won't do anything but as login text is always present there could be no visual way to do this. 
* changing to support request as this is clearer than support article / data. However both agree that this could be handled better by using the original traffic light system discussed - but that would need user testing by @meganwaps 

I understand this change is in. So closing.

**Comment by JosephMcArthur** [comment]
On 1.5 it was saying that I couldn't request data after I'd made an article request: 

<img width="385" alt="screenshot 2016-10-24 00 19 42" src="https://cloud.githubusercontent.com/assets/4953703/19630299/acc3807c-997f-11e6-9e95-002573cd585a.png">

but allowing me to make a request for other articles. 

<img width="402" alt="screenshot 2016-10-24 00 16 06" src="https://cloud.githubusercontent.com/assets/4953703/19630289/4ac051a2-997f-11e6-9394-c5ee8a141e1a.png">

**Comment by markmacgillivray** [comment]
Fixed.
