### ISSUE TITLE
File a bug - remove from plugin?

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/backend#339]
Just thinking, and looking at some other plugins. Do we really need the "file a bug" link at the bottom of the plugin / bookmarklet? We have the bug page on the site, we have links from the plugin to instructions and account page and so on for when different sorts of issue can arise, and from there the user can create a bug - so we could add content to the account and instructions page on the site to link to the bug page, and eventually the bug page will become more interactive anyway (we should add some FAQ under it and I will make it an alternative to the google form once we have time to prioritise it). So we could neaten up the plugin / bookmarklet by just removing this text from the bottom. @JosephMcArthur - does this sound OK?

**Comment by JosephMcArthur** [comment]
Yes. Let's just link the bug page from appropriate error messages. Given our ever decreasing footer size, I'm not averse to a "bugs" link there.

**Comment by JosephMcArthur** [comment]
Removed it from the bottom of the plugin. 

- [ ] add links to Forbidden / Error / unknown error - @markmacgillivray

**Comment by markmacgillivray** [comment]
Done
