### ISSUE TITLE
Button options for download

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#341]
Ideally, we should show just one or two options on each platform - not them all. The rules:

* Where we have a plugin, show that & button in a browser
* Where we don't have a plugin, show the bookmarklet & button in a browser
* On mobile, show button in a browser & #286 

@markmacgillivray if this isn't possible right now showing more is okay. We should just move in this direction.

**Comment by JosephMcArthur** [comment]
If it isn't possible, as long as we're not showing something the user literally can't download then you're good to move this to 4.

**Comment by JosephMcArthur** [comment]
* Seems like cl & ff classes need to be updated to not show up on mobile. 
* Bookmarklet placeholder I have won't show on small screens. 

Adding xs-hidden s-hidden classes to ones with cl or ff causes them to forget the browser specificity.

**Comment by JosephMcArthur** [comment]
@markmacgillivray nudge

**Comment by markmacgillivray** [comment]
Done. User sees firefox or chrome plugin button if on that browser, although for now ff is disabled and says coming soon. If neither of those, then bookmarklet shows. However if on mobile then a mobile blurb shows instead of any of these. In all cases the use in your browser option shows.
