### ISSUE TITLE
Analytics check

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#344]
Mark, do we have:

- [x] Analytics on the website - @markmacgillivray 
- [x] & successfully feeding into an account - Me
- [ ] link / open tracking in mailgun - @markmacgillivray 

Linked to #335

**Comment by markmacgillivray** [comment]
Yep there are analytics on the site, I don't know what you mean by link / open tracking in mailgun.

**Comment by JosephMcArthur** [comment]
for mg.openaccessbutton.org we now have open tracking and link tracking in html messages.
