### ISSUE TITLE
When opening embed window on request pages twitter button disappears. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#349]
@markmacgillivray have you tested the embeds? Just wondering if this is linked to #305 

This can be moved out this milestone once the above Q is answered.

**Comment by JosephMcArthur** [comment]
If they don't work. Then hide them entirely for now.

**Comment by JosephMcArthur** [comment]
** spoiler ** it doesn't work. 

Am currently hiding button & moving this.

**Comment by markmacgillivray** [comment]
Fixed on dev, embed button is showing again and clicking it does not hide the twitter button. We already have another issue open about the embed button specifically, so closing this one.
