### ISSUE TITLE
Move /request/new onto the front page for all users

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#352]
after some progress on find system & #333

**Comment by markmacgillivray** [comment]
This is something that will mean changing the copy of the front page, so I will unassign myself as it cannot be actioned by me until it is very clear what and how it should be inserted into the front page.

**Comment by chealsye** [comment]
It's stupid how hard it is to choose a small bit of words. Let's start with this, but I think it'll need adjustments.

What research do you need? 
We'll help you get access to the article or dataset you need.
[Give us an article URL[
Find It!

**Comment by JosephMcArthur** [comment]
Seems like we could leave the tagline currently there as is, and just have:
>Give us an article URL
Find It!

as we do now on request/new. 

This would mean just moving the 1st bar to the frontpage (as we did once before in #300), but this time I'd just suggest having it right under "Get the articles and data you need". That means the first thing you'd see is that tagline & a box for URL's. Then, if you need more info you can scroll & get that info, and do a deeper sign-up process. 

This change also means we can:
-  [ ] remove find / request request box from /requests. That's never really made much sense. 

We could make other changes here, but, I don't think necessary to move forwards.

**Comment by markmacgillivray** [comment]
@JosephMcArthur I have done this as per how it sounds in the most recent comments, and it is ready to go live. Assigning to you to check it is right, and that it coincides with the outcome you expect between what you suggested and what @chealsye suggested. If happy, please close and it will go live when we decide to push the site update.

**Comment by JosephMcArthur** [comment]
I can respond a touch on various screen sizes, eg, tablet(ish) size 

![image](https://cloud.githubusercontent.com/assets/4953703/20667891/95cee690-b563-11e6-8342-ebeb7f0daa24.png)


it would also be nice if hitting enter made it "find it".

**Comment by markmacgillivray** [comment]
OK, sizing altered for small screens, and enter submits. Closing.
