### ISSUE TITLE
Display sign up message in plugin only when user tries to make a request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#361]
Currently, I think we're displaying this all the time. 

Perhaps, we should only display it when the user wants to make a request (i.e they click the button but don't have an account). That would close #360. 

However, this might mean users don't connect their account to their plugin even if they have one. E.g:
* they sign up
* they click install chrome & get taken to the store off site (not sure if I'm misunderstanding inline install, I probably am)
* they get the plugin
* the **don't** return to the page to join their account / plugin

**Comment by markmacgillivray** [comment]
As commented on the other issue, I think the message should stay all the time but I have removed the wording about the API key. The buttons will no longer click to nowhere, and will say "unavailable" if nothing is available and the user has no api key yet.

**Comment by JosephMcArthur** [comment]
shortened this message in #319. Until we have some more user testing this is all just taste, so I'm happy to close for now. 

@meganwaps if you could pay attention to this message in future user tests that would be great.
