### ISSUE TITLE
Add a spinner / submit message on request submit

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#364]
It can sometimes take a little while for the plugin to finish making a request & giving you the next screen. This left me wanting a spinner or something to reassure me it wasn't an error. Do we want to tell them not to close it yet? 

So, for example, you may have a small spinner on the left & 

> Processing. Don't quit yet. 

where the submit button was.

**Comment by markmacgillivray** [comment]
Small spinner added for loading. Will close now to track what is done, but won't be available until a push later.
