### ISSUE TITLE
Make all email messages html by default

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#366]
This enables tracking, which is important in knowing where things are going wrong in the request system. 

- [x] change
- [x] test
- [ ] deploy

**Comment by JosephMcArthur** [comment]
Came here like "this isn't important anymore", then saw my comment. Turns out it is, well played past Joe.

**Comment by JosephMcArthur** [comment]
Committed to develop. Need testing

**Comment by markmacgillivray** [comment]
Presumably markdown also enables tracking, guessing you mean that by having html content that tracker img links can be inserted into the email? If so, markdown becomes html which can then also be tracked too - so just to let you know, could probably achieve the same goal with html or markdown. did we already enable markdown in the email templating system though? can't remember...

**Comment by JosephMcArthur** [comment]
We didn't enable to markdown to html thing. I've now changed them.

**Comment by JosephMcArthur** [comment]
Okay, have tested the login email now it's html-ified. Works fine.
