### ISSUE TITLE
Monitor Location availabilty 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#367]
Saw the hint of an issue in #365 but not time for a deep investigation. It worked most of the time, so pushing to a later issue to be monitored.

**Comment by JosephMcArthur** [comment]
Just did:
* http://oab.test.cottagelabs.com/request/5iE52hXg6WK7Nk6HN
* http://oab.test.cottagelabs.com/request/z2qqcsGgeaqFo3vRK

on 1.5 & neither had location. This one did:

* http://oab.test.cottagelabs.com/request/3WWF8f7Z5AFydsdYz 

but I don't 100% know the version.

**Comment by JosephMcArthur** [comment]
Above links won't work. Data has been deleted.

**Comment by meganwaps** [comment]
I took a photo of the issue in case others can't get the same issue we're having, Joe. 
![screen shot 2016-10-24 at 11 18 30 am](https://cloud.githubusercontent.com/assets/5968703/19658147/b92e416a-99db-11e6-8bd5-e6702a3acde6.png)

**Comment by JosephMcArthur** [comment]
Yup, data was deleted on purpose to test #358

**Comment by JosephMcArthur** [comment]
Make sure we have the lat & log of a request. This can be seen via the admin interface for requests. Click +detail to see. Either it'll be in orange, or wont be. 

We want to know the 70% of NEW requests that we have location data for.

**Comment by meganwaps** [comment]
All of the requests since Friday have their location, I checked on two separate browsers as well. 
Here's the spreadsheet, I'll add to it every day or whenever new requests are submitted. 

https://docs.google.com/spreadsheets/d/1GKk_Y3wzeXLisMaC-mdS3Zx3tu_uhAoG-q05dKVjZJw/edit?usp=sharing

**Comment by meganwaps** [comment]
We've got 2 requests as of right now that don't have locations, we also have 1 request with an untitled article and a broken link. 
https://openaccessbutton.org/request/saGBPhgdAny8A35iQ

**Comment by JosephMcArthur** [comment]
Okay, this doesn't seem to be a big enough issue to justify more investigation. Closing.
