### ISSUE TITLE
Email to all users telling them to update

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#370]
{{SUBJECT Update Your Open Access Button}}

Hi, {{useremail}}!

We have exciting news - there's a new Open Access Button. You can update your Button right now through your account page: https://openaccessbutton.org/account/

The new Button is simpler and more efficient, and you can now find and request both articles in data in one great service. Once you update your Button, give it a try and let us know what you think!

You can also use our new bookmarklet or search for research in your browser. Learn more about the new changes in our blog post: https://openaccessbutton.org/blog/new-oab-2016

We look forward to continuing to get you access to research,
The Open Access Button team

**Comment by chealsye** [comment]
@JosephMcArthur Here's a draft for this email. Happy for you to tweak wherever needed -- exhausted eyes while writing it. I wasn't sure what the functionality of emails are, so I went with plain text - @markmacgillivray, please do adjust as you need.

**Comment by JosephMcArthur** [comment]
Moving to launchchecklist issue to keep things clean, but this looks great.
