### ISSUE TITLE
space in front of URL on /request/new leads to no requests being found

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#376]
Test URL:  http://www.nejm.org/doi/full/10.1056/NEJMoa1504720 should find 2 requests. 

Just put a space in front and while details will be found, requests won't be. Since most copy will be done from URL bar's where this is hard I'm not expecting this to be a major issue. Just logging for good measure.

**Comment by markmacgillivray** [comment]
I happened to fix this when adding the URL checking to that box, so closing this
