### ISSUE TITLE
Missing fields on old data

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#379]
E.g these requests have no stories when I expect they did. 

Tried it on a couple of requests, including:

* http://oab.test.cottagelabs.com/request/T4hokmZdzGBASGsvK
* http://oab.test.cottagelabs.com/request/3u3xARjRsQoJzeniZ

**Comment by markmacgillivray** [comment]
Nope, neither of them have stories. None of the ten old requests have stories. There's nothing else we can do about that, so closing this issue. Re-open if necessary.
