### ISSUE TITLE
Main page signup box disappears when logged in

### ISSUE THREAD

**Issue by chealsye** [OAButton/backend#383]
@markmacgillivray @JosephMcArthur 
### Expected Behavior

Should the box be disappearing? Is this intentional? If so, what can we put in this space instead?

![screen shot 2016-10-25 at 22 50 25](https://cloud.githubusercontent.com/assets/9299248/19711726/bc0f8ae4-9b05-11e6-90d3-6a06856861cc.png)

![screen shot 2016-10-25 at 22 50 48](https://cloud.githubusercontent.com/assets/9299248/19711722/b5c03cd8-9b05-11e6-81a7-d72983e34d0f.png)
- Software versions: Chrome Version 54.0.2840.71 (64-bit)

**Comment by markmacgillivray** [comment]
Yes, it's intentional. I was under the impression this was the expectation after the decision not to show the URL box for the find search on the front page. There was actually supposed to be a graphic to go in that area rather than a sign up box, but as far as I know it has not been produced yet.

**Comment by meganwaps** [comment]
@chealsye @markmacgillivray Just letting you both know that feedback I was given from multiple user tests indicated that showing the 'Sign up' box after already logging in was quite confusing and could be off-putting for new users. I agree it does look a bit naked, but I'm sure it will look nice once a lovely graphic goes in.

**Comment by JosephMcArthur** [comment]
Moving this back to once we've put more work into the find system, then this is worth implementing.

**Comment by JosephMcArthur** [comment]
Closing this, we should fix it with #352
