### ISSUE TITLE
Bookmarklet on Safari-visuals/no instructions

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#384]
After tinkering with the bookmarklet on Safari (Version 8.0.7 (10600.7.12)) yesterday afternoon, I've yet to been able to make a request using it. 
First off, if I was a first time user this would be incredibly confusing as there's no real instructions apart from the 3 instructions listed underneath the options. 
Second, the text on the bookmarklet does not appear within the text box for 'Request article' 
![screen shot 2016-10-25 at 1 13 14 pm](https://cloud.githubusercontent.com/assets/5968703/19730561/77a9c96a-9b4f-11e6-810e-72cb89c25df7.png)

Third, I believe the bookmarklet might have actually brought safari to a crawl on my computer, as I have many links available to test but the browser cannot locate them when I have the bookmarklet pulled up in a tab. 
I'm worried that the lack of clear instructions might be a huge turn off for new or first time users. 
Please others, let me know if you're experiencing the same issues.

**Comment by JosephMcArthur** [comment]
1. This hasn't really come out of user tests afaik, and there isn't much we can do about it now. Would suggest you continue to keep an eye on this in future tests. 
2. This is probably the same as a bug I reported in #262 
3. Not sure about this one, you might want to pull up your cpu / ram etc usage before / during / after button use

**Comment by meganwaps** [comment]
I'm doing a user test with Graham in a little over an hour, I might slide this in just to see his thoughts/if he can get it to work.

**Comment by markmacgillivray** [comment]
Number 2 I can fix, number 1 if a problem must be the case across everything we're supposed to have user tested already, number 3 doesn't make much sense - can you clarify what you mean by having many links to check, why that would make a difference, and why you think the bookmarklet is making safari slow? And how do you mean having it pulled up in a tab? Are you using the bookmarklet from the bookmarks bar of your browser after putting it there from your account page on the dev system? And are you opening a tab to the URL you want to test on, then clicking the bookmarklet in your bookmarks bar? Are you opening up many tabs for many URLs all at once in the first place? If so safari is going to go slow anyway, whether you use the bookmarklet or not.

**Comment by meganwaps** [comment]
Sorry for not being more specific Mark. 
I mean I have many links to paywalled articles to test. 
The bookmarklet is not even getting installed in my bookmarks bar, it's just popping up within the confines of the test page, but I cannot install it to my bookmarks bar, making it impossible to use. 
This is where the lack of instructions becomes an issue, because if this is happening for everyone, how are users to know it needs to be installed in the bookmarks bar-they might just think it's supposed to work that way. I'm only attempting to open one tab at a time but being logged in to my OAB account in one tab significantly slows Safari. That last issue is probably of my own doing somehow, so I'm going to reset the browser and see what happens.

**Comment by markmacgillivray** [comment]
Ah OK thanks for the extra info @meganwaps 

You should install the bookmarklet from your account page at oab.test.cottagelabs.com/account

You will see a button called OAButton bookmarklet - click and hold down the click, then drag it to your bookmarks bar. Yes, this needs more instructions at this point, I believe @JosephMcArthur and @chealsye are supposed to be coming up with something for the account page.

But once you have it on your bookmarks bar, you should then be able to go to one of the URLs you want to test, as normal, in your browser. Then once on that URL, click "OAButton bookmarklet" where it appears in your bookmarks bar. This should pop it open for you, on that page, just like the plugin extension does for chrome. Then you should be able to test it working on the URLs you want to test on, and it should be the same as the plugin, apart from some layout bugs (which are what we are particularly looking for atm).

I don't know what would be causing your browser to go slow though - the site itself seems to have worked fine on other testing, so unless there is particular evidence of this happening regularly to multiple users, it could be one of many other things on your system, so we can probably ignore that for now, unless it keeps happening to you all the time. We'd probably have noticed that by now though.

**Comment by meganwaps** [comment]
@markmacgillivray you are a gentleman and a scholar! We're in business now.

**Comment by JosephMcArthur** [comment]
Install Instructions would already be in, but my local repo isn't showing the same code as the account page so I was holding off. There will be one or two lines about installing, with links out to better guides for most browsers:

* http://www.howtogeek.com/231775/how-to-install-and-use-bookmarklets-in-microsoft-edge/
* https://crossbrowsertesting.com/faq/how-do-i-install-bookmarklet-google-chrome-mac-os
* https://support.mozilla.org/en-US/kb/bookmarklets-perform-common-web-page-tasks#w_how-do-i-install-a-bookmarklet

I couldn't find Safari though, help appreciated.

**Comment by meganwaps** [comment]
Okay after further use, it's working beautifully! The only thing is that almost every time I click on the bookmarklet, Safari asks if I trust the application. I've checked my security and privacy settings and nothing seems to be amiss. Is anyone else getting this message on Safari when they click the bookmarklet? @natalianorori @chealsye 
![screen shot 2016-10-26 at 12 01 18 pm](https://cloud.githubusercontent.com/assets/5968703/19740612/2cc8c840-9b74-11e6-9a30-98686fe7c9e7.png)

**Comment by markmacgillivray** [comment]
Unfortunately with a bookmarklet there's no way to set it to have default access to your location. It's going to ask every time, or at least every time you first use it in a given website. But if you're seeing that, then it's working!

**Comment by natalianorori** [comment]
Just tested it and it works great for me!!

**Comment by JosephMcArthur** [comment]
when you say it works, did you test:
* finding an article
* make a request (& validating it turned up on the site)
* supporting a request (& validating it turned up on the site)
* being taken to someone else's requests
* getting from the account page
all without errors? 

Sorry to be anal, we just all have different definitions of "working" means.

**Comment by natalianorori** [comment]
sorry, didn't add enough details
- I found articles
- made a request and made sure its up on the site
- supported some requests, was taken to other people's request
- read more into the requests that were made
- was able to sign in from different browsers (chrome and safari) and got
the validation codes fast on my email
- updated and used the new bookmarklet
- used both the browser and the bookmarklet

**Comment by JosephMcArthur** [comment]
\o/ holy hell, we've built something that work good \o/

**Comment by meganwaps** [comment]
@JosephMcArthur I've tested all those aspects as well, with no issue! I just had a quick question, if you are not logged in on the test site will the bookmarklet not work? I've noticed if I go a while (2+ hours) without checking my status on the site, the bookmarklet will give me the 'thinking' ring without any further information. Normally going to the site and logging in again will fix everything, but it could be a nuisance for folks spending a long time researching to constantly have to log in every few hours. @markmacgillivray thoughts?

**Comment by markmacgillivray** [comment]
The bookmarklet will keep working whether you're logged in or not. Older versions would sometimes hang, but if you delete it from your bookmark bar and get it again from /account it shouldn't hang anymore and also now auto updates itself

**Comment by JosephMcArthur** [comment]
Afaik, this is all finished so closing. @meganwaps correct if I'm wrong.
