### ISSUE TITLE
Plugin not supplying correct article

### ISSUE THREAD

**Issue by meganwaps** [OAButton/backend#397]
I'm testing the new version 1.0.3 of the plugin and have discovered that it is not supplying the correct article for a request. 
This has happened to me a few times before, but this time is especially troubling since this is one of my test articles which I use because it has always been correct in the past. 
This occurred on Chrome v 54.0.2840.71 on Mac OSX Yosemite v 10.10.4.

This is the original article I'm requesting:
![screen shot 2016-11-02 at 1 00 03 pm](https://cloud.githubusercontent.com/assets/5968703/19945634/499b8360-a0fe-11e6-9a4b-1d0e6416e5f9.png)

And this is the article the button provides: 
![screen shot 2016-11-02 at 1 00 11 pm](https://cloud.githubusercontent.com/assets/5968703/19945650/5506bba2-a0fe-11e6-9385-3ff82583afb5.png)

As you can see, these are two completely different articles. 
I wanted to inform @markmacgillivray and @JosephMcArthur of this issue immediately, I'm going to test this link on the bookmarklet and website just to see if those provide the correct article.

**Comment by meganwaps** [comment]
The same result occurs now using the bookmarklet on Safari.

**Comment by JosephMcArthur** [comment]
I have assigned this to the next milestone, which is all about the find system (which this relates to).

**Comment by markmacgillivray** [comment]
Note that if you are using the 1.0.3 bookmarklet you are using the latest dev version, so you will get answers back from the dev api - this is good, and a good way to test. But, if you then switch to using the bookmarklet, be sure that you are also using a dev version of the bookmarklet - if you are using it as installed from the live site, then you will actually get answers back from the live API - so they will not necessarily be the same as what you were seeing from the plugin.

In this case, the answers you were getting were the same, so this is just a note for future checking.

Also, a change to the dev API tonight may result in you seeing the correct answers from the dev API now anyway - BUT, this does not resolve the deeper problem so keep this issue open.

NOTE for me: this page when scraped returns a doi for a referenced paper earlier than the doi for this paper itself - tighten up the doi regexes to try to avoid this.

**Comment by markmacgillivray** [comment]
This is fixed on dev - use the find articles page on the dev site and you will see it points you correctly to the arxiv version, and shows the correct DOI in the metadata. I will move this to @meganwaps now for testing.

**Comment by JosephMcArthur** [comment]
Okay, tested this article & it now works! Yay!
