### ISSUE TITLE
on mobile left align all footer sections

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#398]

**Comment by markmacgillivray** [comment]
Fixed on mobile, assigning to @meganwaps to move on to UI testing

**Comment by meganwaps** [comment]
Everything on test site looks great and aligned left! I checked via Safari on iPhone as well as Chrome via Android. 

Thumbs up!

**Comment by JosephMcArthur** [comment]
Thanks @meganwaps. Lets close this!
