### ISSUE TITLE
New mini-icon for the chrome store

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#400]
Instructions:

>Upload an icon image that represents this item, and ensure it complies with the following:
128x128 total pixels
For square icons, use alpha to make 16 of the 128 pixels per side transparent (96x96 visual weight)
For circular icons, the visual icon should be 112x112 (use alpha to make the remaining pixels transparent)
For other icon shapes, use alpha to maintain the same 96x96 visual weight
Additional advice:
Your icon should be flat; avoid noticeable perspective, 3D and shadows.
Don’t use text in your icon.

Can we use the simple logo for this?

**Comment by chealsye** [comment]
![button_96x96](https://cloud.githubusercontent.com/assets/9299248/20084757/7c44df68-a532-11e6-97f1-1bf3da11fbaa.png)

I *think* this is right - but the visual weight trips me up. Not a designer and slowly self teaching...

**Comment by JosephMcArthur** [comment]
Uploaded to store
