### ISSUE TITLE
Archive resources page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#405]
Have looked and seen many issues relating to this page in the backlog. Despite having invested in renewing this page in the last release I now consider that a mistake - it's not required for a core user journey and isn't fulfilling the need we originally created it for. It's also requiring more effort than anticipated to make & maintain. 

So, I want to side step the sunk cost fallacy here and just retire it. 

- [x] leave a note on the page
- [x] remove from the footer
- [x] check for links on the site
- [x] move issues associated with it out of the backlog

**Comment by JosephMcArthur** [comment]
all changes pushed to master in oab_static. Closing.

**Comment by JosephMcArthur** [comment]
@chealsye the copy for this can be seen here: oab.test.cottagelabs.com/resources. Please reopen if you're not happy?

**Comment by chealsye** [comment]
Okay...
