### ISSUE TITLE
Allow users to send emails to authors themselves after making a request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#412]
We could allow them to:
* Send them via our server
* Send them from their own account

Either seems better than we have now, where they have to wait. User feedback suggest folks just want to continue on! We couldn't do this prior due to how the system was designed. Now we can. Both routes seem good to me. 

First step here is estimating the size of changes needed. Seems like we'd need to:
- [ ] have copy for users to email authors themselves
- [ ] allow users to send via our server
- [ ] have UI elements which allowed this
- [ ] have a way to track emails users send for a request

**Comment by markmacgillivray** [comment]
On the request page, which a user is directed to after they create a request, we can add a button that shows for the user that created the request - it can say "email the author". We could also say on the plugin after they create their request "go and do more via the request page" to make it clearer there are more things to do, if we don't make that clear enough already.

Once a user chooses to email the author, we should have them enter an email via the request page, where we should show a text box with a default author email template, just like the admin area already does for you, and then prompt the user to edit the email as necessary. Then they should click to send the email once they are happy with it, and this should update the status of the request. We can also copy the user in to the email they send, so they have a record of it.

I don't think we should push the user towards emailing the author themselves from their own email systems, as then we don't get any further knowledge about the process, and also any user who wants to do that can actually already do it - they just copy the author email address and go from there on their own. So there is no point making this any easier for users.

When a user sends that email, then yes, we need a way to track what email was sent, and what the content of it was. This is something that has come up as potentially necessary elsewhere too, where we not only want to automatically send emails in followup to requests, but also to know what was sent, in case it was customised.

So the UI stuff is easy, then we just need some copy for the author email (which should be very similar to the one the administrator can send, and the main new functionality is recording the emails that were sent about any request, and the content of them, so we can review later if necessary.

It would actually be possible to get info about the emails that are sent via the mailgun account too, but having those logs in the system itself may be more useful.

**Comment by JosephMcArthur** [comment]
I'm not convinced we don't want users to be able to send via their own email. But, we have little actual data on that other than hearsay so let's move forwards where we have agreement & circle back later. 

Okay, that's the decision I wanted to get to for this issue (not this is a discussion / question). New issues on route to break this down. Will reference this.
