### ISSUE TITLE
When not signed in, open article or request buttons don't work on plugin dev 1.03

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#421]
@meganwaps / @markmacgillivray can you try and replicate please?

**Comment by meganwaps** [comment]
@JosephMcArthur I have not been able to recreate this and have made doubly sure that I'm not signed in on the dev site. I'm able to make requests and access open articles without being signed in using dev 1.03. It takes a few moments for the buttons to load, but both work for me, using Chrome, without being signed in. @markmacgillivray were you able to replicate?

**Comment by meganwaps** [comment]
@JosephMcArthur @markmacgillivray I am still unable to replicate this issue. Any luck?

**Comment by JosephMcArthur** [comment]
Alright! Then I'll shut it.
