### ISSUE TITLE
SSL version vulnerability?

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#54]
via bugs@oab.org

---

I tested your server, and you are using a vulnerable version of OpenSSL.
Test results:
https://www.ssllabs.com/ssltest/analyze.html?d=openaccessbutton.org

---

Not sure about this, but passing it on, as I have with the other e-mails I have received.

**Comment by JosephMcArthur** [comment]
@markmacgillivray are we okay here?

**Comment by markmacgillivray** [comment]
We are now fine, some weaker encrypts in use, but this is a safeguard for older browsers that may not support newer stuff. Could review in future and change the ones we allow again.

https://www.ssllabs.com/ssltest/analyze.html?d=openaccessbutton.org
