### ISSUE TITLE
Internal Server Error on Story link

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#55]
via bugs@oab.org

---

Martin Bentley tweeted a link here: https://twitter.com/astonsplat/status/527773907533570048

... and that link points to this address: https://openaccessbutton.org/story/8b3a9bd0deea4cc5842864c707a64eb0

... which returns

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. 

---

It gives me the same error, for what it is worth. The tweet I posted was done through the Chrome addon.

**Comment by JosephMcArthur** [comment]
These are completely redone in new "request pages" - no point addressing this.
