### ISSUE TITLE
Firefox Addon gets wrong metadata

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#56]
Not sure if this is an issue with the Firefox addon or with the backend, but since the addon gets the metadata from the backend, I am opening the issue here.

I hit a paywall at [http://onlinelibrary.wiley.com/doi/10.1111/1365-2478.12078/pdf](http://onlinelibrary.wiley.com/doi/10.1111/1365-2478.12078/pdf) so naturally I hit the Button. For some reason, the metadata it shows is for a different paper entirely: [http://onlinelibrary.wiley.com/doi/10.1111/1756-2171.12014/pdf](http://onlinelibrary.wiley.com/doi/10.1111/1756-2171.12014/pdf) (note the different DOIs). This suggests that the data the addon is getting is incorrect.

**Comment by JosephMcArthur** [comment]
@Steven-Eardley is this good to close with changes made so far?

**Comment by Steven-Eardley** [comment]
Yes, closing this because the Firefox add-on in question is has been deprecated, pending release of the cross-browser extension. That'll have metadata bugs of its own :wink:
