### ISSUE TITLE
Start to search BASE via API for papers. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#61]
Ensure that if there is a version available in base for a paper behind a paywall we can get it!

**Comment by mtb-za** [comment]
According to the meeting today, we have got this more or less done, yes? Close this?

**Comment by JosephMcArthur** [comment]
@markmacgillivray we can shut this, yes?

**Comment by JosephMcArthur** [comment]
@markmacgillivray adding to the current issue and tagging you to ensure we can close.

**Comment by markmacgillivray** [comment]
BASE API is connected in the backend, will be searched as soon as new plugin goes live
