### ISSUE TITLE
"contribute metadata" option when we don't scrape it

### ISSUE THREAD

**Issue by davidecarroll** [OAButton/backend#66]
as we've had problems scraping metadata from certain papers (T+F for example). As an interim measure until the scraper library is built up could we have an option to contribute metadata?

a-la mendeley (see screenshot)
![screen shot 2014-11-25 at 11 45 07](https://cloud.githubusercontent.com/assets/4964180/5182309/9063609a-7498-11e4-8d53-5672f25f7d55.png)

**Comment by JosephMcArthur** [comment]
Adding to this sprint as it's essentially the same #208 . If we don't get this info from the plugin we should get it there.

**Comment by markmacgillivray** [comment]
Moving this onto next milestone, and after we check remote sources (if there is a DOI etc) we can show full metadata on new request page, and allow users to edit it there

**Comment by JosephMcArthur** [comment]
#232 has suggestions for this

**Comment by JosephMcArthur** [comment]
This is also essentially the same as #208

**Comment by markmacgillivray** [comment]
Closing this one as we have multiple issues dealing with this now
