### ISSUE TITLE
Integrate arXiv

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#69]
A major source of physics and mathematics pre-print papers in the the [arXiv](http://arxiv.org).

They have an API, which can return an Atom feed. It looks like it might be possible to search by DOI, if there is one associated with a record. This could be a good place to search for some types of paper.

The API docs are here: http://arxiv.org/help/api/user-manual

I have asked on their API mailing-list if it is possible to search by DOI. Hopefully it is, in which case we can hopefully add them with fairly minimal fuss.

**Comment by mtb-za** [comment]
This looks like it will be doable:
http://export.arxiv.org/api/query?search_query=doi:10.1103/PhysRevD.89.085017

I am not sure if there is a sensible way to limit hitting them only if we suspect that the paper might have a pre-print there or not, but it would be courteous to think about.

It looks like we may be able to serve the pdf directly, since it is included in the response, just btw, but I am getting clarification on whether they have any preference.

**Comment by JosephMcArthur** [comment]
@meganwaps this should be in with base, but can you just validate that (check the base aggregation lists & do a few checks on the live system to ensure we're picking up papers.)

**Comment by JosephMcArthur** [comment]
In testing #397 I can see this works. Closing.
