### ISSUE TITLE
Integrate PubMedCentral

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#70]
PubMedCentral has a large corpus of biomedical research. They also have an OA Subset, which can be searched via API. This only includes genuinely OA stuff: "Some journals use the label "open access" for an article that is available free at time of publication, but is still subject to traditional copyright restrictions. Such articles are not part of this subset."

http://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/

If we can search their (OA) database by DOI, then we could potentially provide a lot of useful stuff to people.

**Comment by mtb-za** [comment]
Their internal search function uses a link along the following lines:
http://www.ncbi.nlm.nih.gov/pmc/?term=10.1186%2Fs12955-014-0151-y%5BDOI%5D

I am not sure if we would be allowed to use this. I will follow-up with them to confirm. It is also very likely that I am missing something in the API docs.

**Comment by mtb-za** [comment]
@JosephMcArthur pointed out that searching their open section will not be too useful, because people already have access to those. (Which I somehow missed.) Although, that subset may not include versions of papers that are available, even if not genuinely open, because it seems to only take things that are CC or similar. I think I should still email to confirm whether they think it would be useful or not for us to poll them.

**Comment by markmacgillivray** [comment]
Superseded by #114
