### ISSUE TITLE
Blog feed doesn't seem to return any posts

### ISSUE THREAD

**Issue by hrickards** [OAButton/backend#71]
See https://www.openaccessbutton.org/blog/feed

**Comment by HLWiencko** [comment]
It looks like the feed contains the latest post. I don't see anything when I subscribe in Feedly, but looking at the feed itself does show the latest post. At the moment MAX_FEED_ENTRY_AGE in settings.py is set to 2592000, which is about 30 days. 

I'll submit a pull request changing it to 6 months and see how we get on?
