### ISSUE TITLE
Reduced Interactivity Option

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#72]
I have been having an interesting chat with someone via bugs@oab.org

Essentially he feels that the Button is too intrusive, what with requiring a story to be entered and is therefore distracting him from finding his research. His request is essentially for a reduced interactivity mode that would essentially just log the paywall in the background, and let him carry on. It seems that he is not using the Button to get access, because he generally searches somewhere else if he hits a paywall anyway.

I am just tossing this out there as an idea, but I am not entirely convinced that this would be too helpful. If we do not get the user story, what are we losing in terms of potential advocacy impact? I am also not convinced on the utility to the user of simply logging a paywall without looking for an open alternative.

---

However, spitballing how this reduced interactivity mode could conceivably work:
I imagine that it would be possible to have a pre-filled in story and no interface and just hit the API with that when the Button is activated. If we are going to do this reduced interactivity mode, maybe we could get a story to use once a day or something and use it for an entire session. Any potential open versions of the paper could be sent as a digest e-mail for the user to look up in their own time.

Please do comment, if you have any thoughts.

**Comment by moorepants** [comment]
I'm the person that brought this up.

For the user story, I usually have a few research projects I work on at any given time. If I could have a list of pre-written user stories for my major research topics and have one as the default, then you could reduce having to type the same thing over and over again and select from dropdown or just let the default user story fly.

**Comment by JosephMcArthur** [comment]
Would an autofill option work maybe? This might be simpler than making a
new interface while still filling the user story.

On 4 March 2015 at 20:00, Jason K. Moore <notifications@github.com> wrote:

> I'm the person that brought this up.
>
> For the user story, I usually have a few research projects I work on at
> any given time. If I could have a list of pre-written user stories for my
> major research topics and have one as the default, then you could reduce
> having to type the same thing over and over again and select from dropdown
> or just let the default user story fly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/72#issuecomment-77234361>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>

Co-Lead/Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe
Skype: joseph_mcarthur
Linkedin: http://linkd.in/1BgZ1jU

**Comment by davidecarroll** [comment]
i like the idea of an autofill

what do you think jason?

thanks,
david


On 6 Mar 2015, at 10:02, Joseph McArthur <notifications@github.com> wrote:

> Would an autofill option work maybe? This might be simpler than making a
> new interface while still filling the user story.
> 
> On 4 March 2015 at 20:00, Jason K. Moore <notifications@github.com> wrote:
> 
> > I'm the person that brought this up.
> >
> > For the user story, I usually have a few research projects I work on at
> > any given time. If I could have a list of pre-written user stories for my
> > major research topics and have one as the default, then you could reduce
> > having to type the same thing over and over again and select from dropdown
> > or just let the default user story fly.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/OAButton/backend/issues/72#issuecomment-77234361>.
> >
> 
> 
> 
> -- 
> Joseph McArthur
> Assistant Director: Right to Research Coalition <http://righttoresearch.org>
> 
> Co-Lead/Founder: Open Access Button <http://openaccessbutton.org>
> Twitter: @Mcarthur_Joe
> Skype: joseph_mcarthur
> Linkedin: http://linkd.in/1BgZ1jU
> —
> Reply to this email directly or view it on GitHub.
> 

David Carroll 
Open Access Button Project Lead david@openaccessbutton.org 
Jabber: davidecarroll@dukgo.com
@davidecarroll
----
My public key fingerprint is 4FFB C540 1284 57FC 5971 2B1A 57DC 89F4 C3F0 BEB3.

**Comment by mtb-za** [comment]
I think that an autofill should work. The window would still appear, but this is probably OK, since it will just be while you record a paywall quickly.

**Comment by markmacgillivray** [comment]
New functionality tracks that a user checked availability of a given page as soon as they click the button. No further information is needed for this simple task, and a login is not even required. So we can now collect more stats on people hitting the button, although we may not know for sure that it IS a paywall. We will be filtering out junk too now though, so at least records of availability should accurately show that somebody wanted the thing, and we could use that count as additional evidence of interest, even if not a fully explained "support". However, at the point that a request is actually needing to be created, this still does require a login and a unique story, which I think is better now that they are like "petitions" - pre-canned stories will not serve the purpose we now need them to serve, which is to convince the author of why "this" item is necessary. I think this one can be closed now, but re-open if further discussion required.

p.s this is all still just on dev, but will become live in about a month
