### ISSUE TITLE
Linking other repositories - APIs for DSpace and ePrints

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#73]
Hi all,

It looks like there are standard APIs for both DSpace and ePrints (which seem to be the most common repository software).

In theory then, if we get a way of using this correctly for each of these, we can probably add new repositories very easily.

I am not sure that most repos will have workable DOI information for pre-prints, but it should allow us to search them using their metadata.

I still need to confirm that this will work how I have in mind though.
Links:
DSpace: https://wiki.duraspace.org/display/DSDOC5x/REST+API
ePrints: http://wiki.eprints.org/w/API
    also: http://wiki.eprints.org/w/API#EPrints::DataObj::Document

**Comment by JosephMcArthur** [comment]
Now, I'd suggest we just notify other aggregators and get them to aggregate (think COS, CORE, Openaire etc). So far, I know CORE will take anything with an PMH link. Now OSF say they're happy to do others via Share.

This was originally connected to #181, but I think it's closeable now as it's not needed by us.
