### ISSUE TITLE
Map doesn't display on small screens

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#79]
This is the case on Android and small screens, on /action.

**Comment by mtb-za** [comment]
Is this a bug or working as designed? Just pinging @markmacgillivray to check that I am not missing anything before I try to fix it.

**Comment by JosephMcArthur** [comment]
If this is working as designed, I'd like it designed differently ;)

On 18 January 2016 at 12:29, Martin Bentley <notifications@github.com>
wrote:

> Is this a bug or working as designed? Just pinging @markmacgillivray
> <https://github.com/markmacgillivray> to check that I am not missing
> anything before I try to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/79#issuecomment-172516244>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment]
:P 

I will see what I can do. Not sure if it will display well, which is why I thought that it may have been left off.
