### ISSUE TITLE
On small screens, menu bar needs to be scrolled to show all options

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#80]
it seems to extend to full lenght, as expected, then retract. Very odd UI.

**Comment by mtb-za** [comment]
The menu height is set to "auto", which is what is causing this. Tracking down where it is enforced now.

**Comment by mtb-za** [comment]
I am not sure what the best way to fix this is.

I have made a change in the bootstrap files themselves, limiting it to 20em, which seems to work in my emulator.
