### ISSUE TITLE
Stick up a header asking people to download the Open Data Button

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#84]

**Comment by mtb-za** [comment]
Does this need to be done immediately, or is this something that will go live later?

**Comment by JosephMcArthur** [comment]
Go live later, but it would be great to get it ready. Could test now, and
then just comment it out or leave good instructions here.

On 19 January 2016 at 09:16, Martin Bentley <notifications@github.com>
wrote:

> Does this need to be done immediately, or is this something that will go
> live later?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/84#issuecomment-172785076>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by markmacgillivray** [comment]
? I don't know what this means. Is it to put a banner on openaccessbutton.org? Seems we are already well past ODB launch, but adding this to openaccessbutton.org is just the usual page edit via the github repo, and push to branches to test then deploy live. No coding required.

**Comment by JosephMcArthur** [comment]
Closed by: https://github.com/OAButton/oab_static/pull/16 which is now in @markmacgillivray court.

**Comment by JosephMcArthur** [comment]
@markmacgillivray anything blocking you here?

**Comment by markmacgillivray** [comment]
Wasn't sure if you still want it, and where. As a banner across the top of
the front of the oab site?

**Comment by JosephMcArthur** [comment]
I still want it, see my last comment. I want a quick ?code review? as
development doesn't line up with master.
