### ISSUE TITLE
Put up a graphic asking people to download the open data button on our slider

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#85]
@mtb-za you'll need to ask Chealsye to do a slider for this.

**Comment by mtb-za** [comment]
@markmacgillivray: Can you confirm that this just needs to be saved to the `portality/static` folder in order to work?

Or should we put this on flickr or something else?

**Comment by markmacgillivray** [comment]
Yes you can put it in static and refer to it from the pages via
/static/yourfile.jpg or whatever.

**Comment by markmacgillivray** [comment]
This is just a content edit. Can be done in the oab_static repo, put the appropriate file in the static folder, then link it in the slider where desired. Will leave open but remove myself from assignment.

**Comment by JosephMcArthur** [comment]
@chealsye can you take a stab at this? You've probably got a better grip on the file needed. 

Can you also - [ ] update the readme to include a not on how to add sliders

**Comment by chealsye** [comment]
@JosephMcArthur OK I made a graphic slide in (static/odbforoabsite.png), but when I went to update index.html I messed it all up. The OAB slider currently uses text whereas the ODB slider uses images. I'm not sure what to do to make the image work in the OAB slider, when I tried to use a slice of the code from the ODB slider it messed up the whole slider on the site...

**Comment by JosephMcArthur** [comment]
Okay. Thanks for trying Chealsye. We could try a text slider, which may be easier, or since #84 will soon be done just forget about this. I'm ambivalent either way.
