### ISSUE TITLE
Add a landing section to the About and Support pages - Need copy

### ISSUE THREAD

**Issue by mtb-za** [OAButton/backend#87]
Discussion started in #82 which included that we do not want to go directly to funding in support.

This is a minor edit that just needs copy in order to be made to work.

**Comment by mtb-za** [comment]
There is a message for where this edit needs to happen on the respective pages, in case someone else needs to edit the copy. (And so that I remember what the heck I need to do once it is completed.)

**Comment by JosephMcArthur** [comment]
Text for this:
https://docs.google.com/document/d/1HDdVZYc6X3WiTBW0ORMo_BTtIvwC88GO5pqlqGkKdAs/edit

This should be good to go, but I'd like to push all this live more or less
at once.


On Monday, 18 January 2016, Martin Bentley <notifications@github.com> wrote:

> There is a message for where this edit needs to happen on the respective
> pages, in case someone else needs to edit the copy. (And so that I remember
> what the heck I need to do once it is completed.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/87#issuecomment-172541516>.
>


-- 
Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>

Co-Lead/Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment]
Have done this for both pages.
