### ISSUE TITLE
"Thanks" tab duplicates on the About page 

### ISSUE THREAD

**Issue by alexgiann** [OAButton/backend#90]
I had an issue with the “Thanks to” tab. All tabs look fine when you open them but if you click on the "thanks to" one and then go to any other tab, the text of the “Thanks” tab is duplicated on the bottom of the other tabs you open. It only happens with this one as far as I have noticed, the others go away just fine.

**Comment by mtb-za** [comment]
This is weird. I have no idea why it is doing this.

Everything seems to check out, code-wise. Can someone else take a look as well? Maybe I am missing something.

**Comment by mtb-za** [comment]
Seems to be fixed.
