### ISSUE TITLE
Issue with expandable cards on /advocacyresources

### ISSUE THREAD

**Issue by svmelton** [OAButton/backend#97]
The expandable cards on https://openaccessbutton.org/advocacyresources need some love—they currently are not styled correctly and are not expandable. We'll need some help with Javascript.

**Comment by mtb-za** [comment]
I will get on this as soon as I can access the etherpad. It is not loading the actual page content for me right now.

I do see that there are some Bootstrap cards that have been commented out, just as an aside.

**Comment by svmelton** [comment]
Yup! I added those in as a possible alternative to the other cards, but Joe wasn't sure about their ability to open independently in mobile.

**Comment by JosephMcArthur** [comment]
It's fine to use those now. See here:
https://docs.google.com/document/d/1h3sMqdm3zqOJdII_7GSsjVGtojoWCiSksqKM8ZdhCm0/edit?ts=56bd1476#

On Thursday, 25 February 2016, Sarah Melton <notifications@github.com>
wrote:

> Yup! I added those in as a possible alternative to the other cards, but
> Joe wasn't sure about their ability to open independently in mobile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/97#issuecomment-188960974>.
>


-- 
Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>

Co-Lead/Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment]
This has been moved to https://openaccessbutton.org/resources/

**Comment by mtb-za** [comment]
These are fixed, although I am pushing a new css file now to alter the bootstrap buttons and nav-pills to use one of our blues instead of the default.

Buttons will also go orange on hover.

This page still needs copy.
